### ISSUE TITLE
DTOs created within a project are not showing

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1030]
Shesha framework DTOs are showing, however if you create a DTO within a specific project it does not when you want to bind a form to it/searching on the entity configs but exist on the code

**Steps to reproduce the behavior:**
1. Create a new DTO
2. Navigate to the frontEnd and search for the DTO when selecting an entity on the form/on Entity Configuration

**Expected behavior**
The DTOs should display

NB: Please add a testing on Function Site for testing purposes

**Comment by AlexStepantsov** [comment]
This works as expected
To use Dto in the lists of UI, it must be used in some service. The list of available DTOs is formed from the description of endpoints
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/3e94b5b9-7901-48b4-92a2-3d2a2be10cea)
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/5ee82088-ae7a-471f-977a-b94242db5f20)
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/74c90e4a-e2fa-4986-b22b-c5b8375225ae)

**Comment by ihouvet** [comment]
@AlexStepantsov  I am assuming that this is getting picked up via reflection.
The team noticed that if the end point returns a list (e.g. List<AlexTestDto> or IEnumerable<AlexTestDto>) it will not get picked up.
Can we:
 1) Support lists, and
 2) Support an attribute that can be added a class level for forcibly include or exclude the class from the list of models?
