### ISSUE TITLE
Dropdown component value format property updates fail to save in dataTable

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1045]
After attempting to modify the value format of a dropdown component within the DataTable, changes fail to save. For instance, updating the default value from 'simple item value' to 'reference list item' . Upon revisiting configurations, the value reverts back to the default setting

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=7c46835d-4b02-401d-98d8-04c90574e99c'
2. Click on 'dataTable'
3. Scroll down to 'membershipStatus'
4. Click on `configure` button on edit/create component property
5. Update `value format` value to any of the options available
6. Save your changes
7. Refresh the page
8. Navigate back to your configurations and check the value format you've updated
9. Actual Results: The value format has reverted back to the default value

**Expected behavior**
When you update value format, the changes should be saved successfully and not revert back to the default value

Related item
#1039

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov , I've re-open this item. After the implementation of this item: https://github.com/shesha-io/shesha-framework/issues/1056, the changes you added have been reverted back

Here's a new link: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=9230268b-aaf4-433c-8c1c-82a1b079a1c0

**Comment by AlexStepantsov** [comment]
Dropdown in the DataTable works only in Simple mode due to validation limetation

We will improve this if there are corresponding requirements in real use
