### ISSUE TITLE
Failure to append Newly created record ID to URL after successful execution of script method

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1068]
In a case where you want to create a record using execute script method, then you handle success and navigate to details view, currently when navigating, on the details view the newly created ID does not get appended on the URL which results in the form being empty.

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/Books-Table'
2. Click on 'Add'
3. Enter the required details
4. Click on 'Save' button afterwards
5. Click 'Yes' on the pop-up
6. Actual Results: When you land on the details view, the fields are empty and when you check on the URL the ID is not appended

**Expected behavior**
Immediately when the form navigates to the details view, the newly created ID should be appended and the data should be recorded on the fields

https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/book-details?id=
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/06ccf725-9c4c-4e48-a84c-31025a009e82)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
