### ISSUE TITLE
Align the width of `Properties to fetch` field to be the same as the other fields

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1133]
The width of the `Properties to fetch` field is smaller than the other fields

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=4de5b167-8f56-493f-a85a-1805e8c2f442'
2. Click on 'dataTable'
3. Click on 'customize Columns'
4. Click on the last column 'Residential Subform'
5. Check `properties to fetch` field
6. Actual Results: The size of the width is smaller than the other fields

**Expected behavior**
Be consistent, increase the size of the field to align with the other fields

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/8de84970-6585-4860-a7e7-6e33c8784ce9)

**Comment by AlexStepantsov** [comment]
There is "+" button
