### ISSUE TITLE
The login page should be converted to a configurable form

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1158]
To make the application look and feel more configurable, the login page should be turned into a configurable page.

** Acceptance Criteria **
- Login page should come pre-configured with Shesha
- Login page should be a configurable page
- There may be a need to add an AppSetting to specify the log-in page to be able to point to updated one
- Same applies for both the admin and public portals
- How to article should be added to the documentation

**Comment by hlayisanimazuze** [comment]
A user will be able to change how the view should be on the login page: https://github.com/shesha-io/shesha-framework/issues/1449 when the login is configurable. I will close item 1449 and will be tracked after the implementation of the login

**Comment by Tshepiso-R** [comment]
The requirement "There may be a need to add an AppSetting to specify the log-in page to be able to point to updated one" has been cut out.

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, there's a requirement for documentation on this item. Can you please complete the documentation before updating the item

**Comment by Lukeybooi** [comment]
@hlayisanimazuze this is resolved. As we discussed I will do the documentation separately.
