### ISSUE TITLE
Provide additional options to configure the Panels component look & feel

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1159]
**Is your feature request related to a problem? Please describe.**
To make the panel component more suitable for use on public portals, additional configuration options should be provided.

**Acceptance Criteria**
1. The following properties should be configurable to provide more.
   1. Header background colour
   2. Body background colour
   3. Show/Hide Border styling
   4. Separator show/hide/styling (the bar/line between the header and body)
   5. Show/hide top bar
   6. Corner radius

7. The set of CSS classes that can be overidden to change the default look and feel should be clearly documented

**Comment by Tshepiso-R** [comment]
NEed to create new issue for Corner Radius support

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, can you please assist with the documentation for item number 2?

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, this item is not complete

Requirement 2: The set of CSS classes that can be overidden to change the default look and feel should be clearly documented, mention you should document the CSS classes you can use to override the default look and feel. Please check this and provide the information. Suggestion you can also add info to the property tool tip/link to the documentation

**Comment by Tshepiso-R** [comment]
Hey @Lukeybooi, please see @hlayisanimazuze's comment. Please provide documentation of the set of CSS classes that can be overridden to change the default look and feel
https://github.com/shesha-io/shesha-framework/issues/1159#issuecomment-2079036475

**Comment by hlayisanimazuze** [comment]
https://dev.azure.com/boxfusion/Shesha%20Web%20v3.0/_wiki/wikis/Shesha-Web-v3.0.wiki/1107/Public-Portal-Styling
