### ISSUE TITLE
Incorrect Module appended to reference list endpoint

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1171]
When a Reference List, such as SheshaEnterprise.SalesOrderStatuses, is created and exists in a different module, such as Shesha Enterprise, but is used in the Sales Order Module, the getByName endpoint incorrectly appends the SalesOrderManagement module to the payload as if it exists within that module.

![image - 2024-03-13T092922 652](https://github.com/shesha-io/shesha-framework/assets/151041759/dfd09487-0b77-4d7c-ba57-8ea75523f20e)

![image - 2024-03-13T092915 127](https://github.com/shesha-io/shesha-framework/assets/151041759/8b3af1f2-e07a-48c1-a08a-ebbafff7a885)

While the reference that exists on the system is the below example
![image - 2024-03-13T092911 179](https://github.com/shesha-io/shesha-framework/assets/151041759/a6470905-54b6-4670-9546-235fc165bc89)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. If the Module is not specified for a reference list property we search reference list in the entity owning module. I've made changes in the pd-enterprise and it should work after update of your project. Please create a separate card for code clean-up and documenting of the reference lists functionality.
