### ISSUE TITLE
The value of file and file list does not show when you are on the details view read mode

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1220]
When a record has attachments on a file and file list, the information does not show when you land on the details view of the record. It only shows when the form gets into edit mode

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/entityPicker-details?id=3e8ad044-d3bc-4a74-bf5c-26b7577fd184'
2. Check file and file list fields
3. Actual Results: The attachments does not show
4. Click on 'edit' pencil
5. Actual Results: The attachments shows

**Expected behavior**
When you navigate to the details view, if the record has file attachments, the files show should same as how the other form fields values are showing. Example of where it is working: https://function-v0-32-adminportal-test.shesha.dev/dynamic/Shesha/test-cascade-behavior-details?id=a59b78d0-c2fa-4219-ac2a-003f12718f28

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/c4bbf7ee-babc-4667-af04-bb98ef22f5b1)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/b31b3398-2473-42cd-ba6c-673f382ec38f)

**Comment by hlayisanimazuze** [comment]
Related item
#579

**Comment by AlexStepantsov** [comment]
Fixed with another changes
