### ISSUE TITLE
A list of properties that require completion of integration with the Monaco code editor

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1229]
Some properties impact multiple components across the system. Only the property names are listed here, but updates should be applied to all components utilizing these properties

The changes should also be extended to the dataTable inline components settings

1. Events properties such as:
    - On Change
    - On Focus
    - On Blur
    - On Select
2. Validator
3. Style
4. Wrapper style
5. Subform 
    - Query Params
    - Get Url
    - Post Url
    - Put Url
    - Actions
        - On Submit
        - On Created
        - On Updated        
6. Progress Component
    - Format
    - Success
  7. Markdown Component
        -   Content
8. Image Component
    - Data Source type `URL`
    - Data source type `Stored file Id`
9. Custom Icon and Custom Color (Icon Picker)
10. On File list Changed
11. Child Entities Tag Group
    - Label Format
12. Statistic Component
    - Title Style
    - Value Style
13. Radio and Checkbox Group
     - Data Source URL
     - Reducer Function
15. Dropdown Component
    - Item Custom label
    - Key value
    - Custom Value
16. Datefield
    - Disabled Date Func
17. Autocomplete Component
      - Default Value
18. DataTable Component
      - Table container style
      - Table style
      - CRUD Operation Expression(Can edit, Can add and Can delete)
      - New row init
      - On row save
      - Custom Visibility (Also exist on Wizard Component)
19. DataList Component
      - Style of group headers
      - New list item init
      - On list item save
      - Form identifier expression
20. Section Separator
      - Container Style
      - Title Style
21. Wizard Component
      - Custom Enabled
      -
22. Exposed variables doesn't accurately reflect all the variables exposed. Example: contexts variable is exposed but only visible  when arguments are logged and not in the region 
23. The code validation and syntax sometimes highlight code that is syntactically correct. Example: arguments

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've updated components, you can check. Regarding item 22: syntax parsing sometimes takes tome time, later I'll add a visual progress indicator (need to check support from Monaco-editor first), `arguments` is highlighted because of usage of typescript syntax. It's supported by default in javascript but not in typescript. We have to ignore it for now because later we'll use typescript with compilation.

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , I've created a separate card and added it on the backlog for the outstanding component, mostly is a styling property. We will revisit when there's capacity
