### ISSUE TITLE
If the `permanent filter` within dataTableContext is set to required, on render it does not apply the filter it acts as an optional filter than the required one 

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1232]
If you set permanent filter to required, when the filter is executed it acts as an optional filter instead of required

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=0964f73a-a16d-404a-86e6-04da8f59131d'
2. Click on 'dataTableContext'
3. Click on 'permanent filter'
4. Apply a filter and set it to required
5. Save and preview
6. Actual Result: All data gets displayed without applying the filter

TableViewSelector works correctly. When the filter is required, it applies the filter immediately

**Expected behavior**
When a filter is set to required, on render it should apply the filter as configured

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , let me review this item once this item: #1300  is fixed before investing time on it

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, you can check
