### ISSUE TITLE
An error occurred gets displayed when editing the side menu

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1256]
When you try to edit the side menu configurations, immediately when you click on it, an error gets displayed

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/
2. Switch the live mode to edit mode
3. From edit mode, click on the side menu
4. Actual Results: `An error has occurred, `useFormActions must be within a formProvider` gets displayed

**Expected behavior**
The side menu should be editable immediately when clicked from edit mode setting

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/800202f0-8329-4bcd-925e-03b5af591f82)

**Comment by AlexStepantsov** [comment]
@nthangeniphumudzo 
Error due to your changes
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/c1e78391-bae2-4599-9b3d-5760d795ad05)

**Comment by nthangeniphumudzo** [comment]
@AlexStepantsov  Noted . I will evaluate when I get to the office quick. Thanks
