### ISSUE TITLE
When `is dragger` set to true,  file list components icon and attachments colour are not updated dynamically according to the theme color

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1261]
When the file list component is set to use the dragger functionality, the default icon and files do not change the color based on the primary theme colour

**Steps to reproduce the behavior:**

1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/entityPicker-table'
2. Click on 'Add' button
3.  Check the file list components icon color
4. Click on the component and select a file from your file explorer to upload
5. Check the color of the file
6. Actual Results: The color is blue, while the theme color is a different color. Compare the colors displaying on the file List and file

Expected Results
The file list icon and the attachments should dynamically adapt the primary colour

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3525ba67-ebce-4643-a405-3049487d70e1)

**Comment by AlexStepantsov** [comment]
Hi @hlayisanimazuze 

@czwe-01 made changes and now it works as expected. Are there other issues?

![image](https://github.com/shesha-io/shesha-framework/assets/125558744/ff7013df-f235-4e45-bc2a-cde33fd36e9d)

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov , I will check it
