### ISSUE TITLE
`Failed to resolve id` error gets displayed when accessing form details, permission and employeeAccount

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1285]
When accessing the details view of a form, permission  and employeeAccount an error gets thrown. These are the entities I've come across, if it is a global issue, please fix it globally

**Steps to reproduce the behavior:**
1. Go to :
- https://function-adminportal-test.shesha.dev/dynamic/Shesha/permission-configurator
- https://function-adminportal-test.shesha.dev/dynamic/shesha/form-details?id=e19019b9-c15b-437f-936a-d23b80c29dcd
- https://function-adminportal-test.shesha.dev/dynamic/Shesha/employeeaccount-table
2. Open your console
3. Check the error being displayed
5. Actual Results: `Failed to resolve type id for class Shesha.Web.FormsDesigner.Dtos.FormConfigurationDto`. Same error about failed to resolve type id gets displayed on all the above links

**Expected behavior**
The link should be accessible successfully without the error being thrown

NB: For form and permission, we had to replace the Dto with the entity and it was able to work
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a61f61a9-3b87-45d7-ae65-c34a4fb0fe3a)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, you can check
