### ISSUE TITLE
When you use `{{data.id}}` on filters, it does not pass the id

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1295]
When you apply a filter on `dataTableContext` and permanent filter, the id does not apply. I
- If you use `tableviewselector `component, it does pass the property name, however it does not pass the data id
- If you use permanent filter from the `dataTableContext`, the filter does not get pass. There's a separate item created to address this

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/abc1-details?id=81514aee-4173-4ec0-b8c3-50212a995919'
2. Check the membershipPayment child table
3. Actual Results: The id is not appended on the endpoint

**Expected behavior**
The data.id should pass the id onto the filter

<img width="958" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/6652ffeb-c7a7-4bfd-a791-0bc179c6292a">

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, you can check
