### ISSUE TITLE
When a filter is dynamically applied based on the selected value e.g. {{data.selectedAddress.id}}, the getAll endpoint is not being called after the selection

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1300]
If the dataTable should be filtered based on a value selected/provided from any of components, after selection the getAll does not get called after selection. Example: On this form https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/filteringchange-form?mode=edit: Address, Email, Gender and Bank. If you use any of the fields, immediately after selection, the getAll endpoint does not get called, which results to the data being unfiltered. 

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/filteringchange-form?mode=edit'
2. Click on ' Select Address' autocomplete and select a address
3. Check inspection to see if there's any address being called
4. Actual Results: The getAll endpoint does not get called after selecting a value to apply the filter

**Expected behavior**
 When a value is selected, the filter should trigger a call to the endpoint, resulting in the data being updated accordingly

Example of configuration that is working accordingly: https://function-v0-32-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/testform1-create?mode=edit

See attached video

https://github.com/shesha-io/shesha-framework/assets/151041759/1f7cebee-be48-407a-b394-663c1553fd14

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, you can check
