### ISSUE TITLE
No-auth page redirection does not work on specific projects

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1307]
The no-auth page redirection does not redirects after entering the username of Stater and Project Management project 

**Steps to reproduce the behavior:**
1. Go to 'https://pd-projectmanagement-adminportal-test.shesha.dev/no-auth/shesha/forgot-password?mode=edit' or 'https://starter-adminportal-test.shesha.dev/no-auth/shesha/forgot-password?mode=edit'
2. Enter 'Username' and click on 'Next' button
3. Actual Results: Immediately instead of redirecting to the next page from the reset password configurations, it redirects to the login page. The reset password requires a user to be login first

**Expected behavior**
The no-auth page should work without a user logged in. After the username, the next button should redirects to the next page of the reset password based on the configurations

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've updated code of starter  template
