### ISSUE TITLE
Allow API security to be configured

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1321]
### Overview
Dynamically generated standard CRUD APIs for Entities should NOT be configured through this interface, rather that should be done through Entity Configurator already implemented. This API Configurator applies to all other custom APIs.

The user should be able to view all Endpoints exposed by the application and specify what Permission(s) should be required to access it.
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/0d23248d-4ffa-4d9a-bb47-8c53d142b050)

### Acceptance Criteria

1. Dynamically generated standard CRUD APIs for Entities should NOT be configured through this interface, rather that should be done through Entity Configurator already implemented. This API Configurator applies to all other custom APIs.
2. Note the following changes from the original Mockup that was shared:
   1. We allow Persmissions to be specified at a Service as well as at an end-point level
   2. Category property is no longer specified at the end-point level as it is rather done at the Service level
   3. It is possible for all end-points to simply inherit authorisation settings from the Service it belongs to
3. The Services and Endpoints tree view should indicate to the user the accessability status of the Services and Endpoint
   1. In the mockups we use additional icons, but if the Treeview component does not support icons then we can simply add the following next to the Service or End-point names" '(Disabled)", "(Authorized)", "(Permissioned)", "(Unsecured)"
4. The user should be able to specify the Access settings at a Service level and all end-points underneath will inherit by default
5. If Access = Disabled, the application should not even expose the End-point or Service
6. If Access = Allow Anonymous, the end-point should not even require an authenticated user to access
7. If Access = Requires Permission(s), the 'Required Permissions' component should be displayed and the user should have to select one or more Permissions.
8. If Access = Any Authenticated User, then any user that has been authenticated should be able to access the End-point.
9. If a user attempts to access an end-point without having been assigned the required Permissions an Authorisation exception should be returned
   1. In debug mode more information should be returned to the user e.g. If the end-point was Disabled, or Required Permissions looking for,

**Comment by AlexStepantsov** [comment]
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/6d012eb3-1b5d-4aae-bc4a-04a07e8895ed)
