### ISSUE TITLE
Screen size option buttons on the form configurator  stack vertically on an iPAd

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1322]
**Steps to Reproduce**
1. Open the form configuration form using an iPad
2. Error: See the screen size buttons alignment below
<img width="1366" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/21078025/83664f62-281d-4a03-948e-e783887222fb">

**Comment by hlayisanimazuze** [comment]
Hi @nthangeniphumudzo, 've tested this item, and with the latest changes on Function, it is still not resolved. Please check if your PR has been approved. I see that the above PR is still open
