### ISSUE TITLE
Navigation ‘links’ and buttons should behave as regular URL based links to take advantage of native browser functionality

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1326]
### Overview
Currently navigation ‘links’ and buttons in Shesha do not behave as normal links rather they execute JavaScript, which causes the navigation. The problem with this is that we are unable to take advantage of native browser functionality, such as mouse, clicking, and opening in a separate tab.
Some users, including myself, find this extremely useful, but it’s not possible in Shesha.
This is in particularly limiting for the main menu items and the drill down/action columns on table views typically used to view or edit details of an entity.

### Acceptance Criteria
1. Hovering over a main menu navigation item should display the URL. The item will navigate the user to in the browser footer as per standard behavior for a link.
   1. Right mouse, clicking on a main menu navigation item should offer the standard options to open the destination in a new tab or a new window
1. Hovering over a navigation column (e.g. view details or edit column) on a data table should display the UR in the browser footer as per standard behavior for a link.
   1. Right mouse, clicking on a the navigation column should offer the standard options to open the destination in a new tab or a new window

### Current Behavior
<img width="1366" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/21078025/180e8541-a170-406f-ab6c-cf719bc301e9">

### Required Behavior
<img width="1366" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/21078025/7f3100df-6d65-4923-bb3d-0b0ea8f4feae">

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi , please set this card to `readyForTesting `once all the items are resolved

**Comment by hlayisanimazuze** [comment]
Closing this item. Any issues arising we will be linked to this card. What's outstanding is #1598
