### ISSUE TITLE
There should be a standard form to display an entity, audit trail

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1349]
### Overview
Currently the framework is able to create an audit trail for any meaningful actions on an entity and or data changes on track properties. However, there is no mechanism to easily display that audit trail.

### Acceptance Criteria
1. Create a standard form that may be displayed in a dialog box to view the audit trail of an entity.
2. The form should accept 3 parameters:
   1. EntityType - the name of the type of the entity whose audit trail should be displayed.
   2. EntityId - the idea of the entity whose audit trail should be displayed.
   3. IncludeEventsOnChildEntities - If true, the audit trail should also display audited events for child entities.
3. The details for template should be updated to include a history button on the toolbar which displays the entity audit trail in a dialog box
4. If an end user clicks on the history button and dialog box should be displayed listing the full audit trail displayed as a Datta list in the following formats.
5. Events should ordered with the most recent events on top

————— Template for properties updated event———————————
{EventDate} {EventTime} - {user name} updated:
* {Property1 changed name} from ‘{prev value}’ to ‘{new value’
* {Property2 changed name} from ‘{prev value}’ to ‘{new value’
* …
————Template for custom event———————————
{EventDate} {EventTime} - {user name}: 
{Custom event description}

**Comment by hlayisanimazuze** [comment]
Awaiting for a childEntity property that I can use to test with before finalizing the item

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, please check requirement 5: Events should ordered with the most recent events on top and update accordingly. Currently, the most recent item is listed at the bottom and old on top
