### ISSUE TITLE
Rich text editor component breaks when switching to JavaScript placeholder

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1387]
**Description**
Upon attempting to switch the placeholder of the Rich Text Editor component to JavaScript, the entire functionality of the component breaks down.

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/twenty-three-details?id=9e58861b-2b22-48e9-a5ab-05fddd8cfe13'
2. Navigate to form designer
3. Click the Rich Text Editor component
4.  Click the placeholders's JS button

**Actual Behaviour:** 
The component breaks and displays the error "An error has occured
i18n: Need string in first argument"

**Expected behavior**
Switching the placeholder property to JavaScript should not break the functionality of the Rich Text Editor component. Users should be able to utilize JavaScript for dynamic placeholder content while retaining the core functionality of the editor.

**Screenshots**
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/a0bbc690-1b50-4e03-9db0-5e76bce3e94f)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/3b953553-2907-4be1-a5e8-1d32a0fda2c7)

**Comment by hlayisanimazuze** [comment]
Added as part of release 0.34
