### ISSUE TITLE
When files are attached to the `fileList` component before an entity is created via `execute script`, those files do not get saved under that entity

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1407]
When creating a new record and attaching files using the file list component with the default buttons action, the attachments are saved under the entity as expected. However, when using the execute script action, attachments created prior to entity creation are not saved. If the entity is created via execute script and files are attached in the subsequent step, they are successfully saved onto the entity. There is also a need to support the same scenario to allow attachments to be created before the entity has been created via execute script

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/book-formatting'
2. Click on 'Add'
3.Enter all the required information, including attaching files and click on save
4. Afterwards, check the record created to see whether the attachments have been saved under the entity created
5. Actual Results: The attachments are not saved

**Expected behavior**
The files attachments uploaded via file list should get saved under the entity created

**Comment by hlayisanimazuze** [comment]
Related Item
- #1373

**Comment by hlayisanimazuze** [comment]
@AlexStepantsov, I've noticed on the payload _delayUpdate does not get show on the payload when using execute script, could that be the reason like how the default buttons does. The below screen is from the default buttons
<img width="952" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/17d0058d-113f-4920-8c35-23ed5a59b187">

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, after fixing item https://github.com/shesha-io/shesha-framework/issues/1373, this bug got re-introduced. Currently I am able to create a new record using the execute script/custom buttons, however upon submitting successfully, when you check the files attached under the newly created record are not there. The request payload does not append _delayedUpdate like how it is when using a default buttons

1. https://function-adminportal-test.shesha.dev/dynamic/TestModule/newOne-table
2. Click on execute script button
3. Enter the details including attaching files
4. Submit
5. Drill down to the details view of the record you've created
6. Confirm if the files are record on the details
7. Actual Results: The files are not listed under the record

**Comment by AlexStepantsov** [comment]
Hi @hlayisanimazuze 

fixed, need to use `form.addDeferredUpdateData(data);`

![image](https://github.com/user-attachments/assets/57eeaba6-3ed0-430f-9ae7-72259afc32c2)
