### ISSUE TITLE
Dragging and dropping an item outside a group on the side menu results in duplicating the item

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1415]
If a item is dragged and dropped outside a group, it duplicates the item

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/'
2. Click on 'Live Mode' switch and set it to edit mode
3. Click on the side menu and click on a group configured
4. Drag and drop an item outside the group
5. Actual Results: The item dragged outside duplicates

**Expected behavior**
When an item is dragged outside the group, it should not duplicate the item

Video: https://boxfusionint-my.sharepoint.com/:v:/g/personal/hlayisani_mazuze_boxfusion_io/EYmsMN0jpQtIv8ZiJ_EeiNQB9eD_Kabb32-shu1fPjYAhA?e=iumGEX

**Comment by hlayisanimazuze** [comment]
Related item: #1166

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , I encountered this bug when I was checking this item: https://github.com/shesha-io/shesha-framework/issues/1618. I will be able to confirm whether it is resolved or not once the new bug has been fixed
