### ISSUE TITLE
Change icon to Hamburger menu with text

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1450]
Currently this icon illustrated in the screenshot is quite small and has potential to be missed. 

Can we kindly turn it into a Hamburger Menu icon with supporting text to say Menu similar to how all the other menu items are. This creates a bit more consistency on the Navbar items as well as reduces risk of user frustration by missing this. 

![Menu](https://github.com/shesha-io/shesha-framework/assets/153498650/2a13bdf7-fcbf-464b-ace2-d65adcfeb66a)

Here is a link to a Hamburger menu icon if you want to see exactly which one it is. 
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amenu%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi , the requirement is not complete. It requested to change icon to Hamburger menu with text. The changes available on the public Portal is the Hamburger icon, however the supporting text to say Menu is not added

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/df4692cd-65f0-487f-9865-ef300328c878)
