### ISSUE TITLE
Alignment on Libraries folder text

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1451]
On this component can we please reduce vertical space from text to folder icon by a small amount as well as center aligning the text to the icon horizontally. 

![Alignment](https://github.com/shesha-io/shesha-framework/assets/153498650/9c2bf9d4-e601-4954-beb7-f24ecbc56aac)

**Comment by Lukeybooi** [comment]
Hi @AlexanderSlavchovUX @hlayisanimazuze can we kindly raise the implementation of this on the admin portal level or create a specific component to cater for this instance.
