### ISSUE TITLE
FAQ screen updates

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1453]
Can we kindly horizontally center align this section on the FAQ screen
![FAQ1](https://github.com/shesha-io/shesha-framework/assets/153498650/7ea317f9-390f-46aa-b4ab-6d4be2e210df)

And can we kindly make the default state for titles on the dropdown bold
![FAQ2](https://github.com/shesha-io/shesha-framework/assets/153498650/f43efbda-18a1-4524-a022-a910849d6dda)

**Comment by Lukeybooi** [comment]
Hi @AlexanderSlavchovUX the centering of the text can be done through configuration.
