### ISSUE TITLE
Wizard Stepper Icons need to be vertically centered

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1454]
Can we please vertically align the stepper wizard icons so they are centered to the Details and description. Currently they are centered to the top field and it causes the icon to protrude too high. 
![Wizard](https://github.com/shesha-io/shesha-framework/assets/153498650/cc931ecd-50af-420f-b3a8-a9dd5a18b2c5)

**Comment by Lukeybooi** [comment]
The placing is correct. If the placing of the icon shifts it will be off placement when there isn't a description. 
![image](https://github.com/shesha-io/shesha-framework/assets/33176583/0e75838b-b554-4f05-a74d-a5ed503318b4)

**Comment by AlexanderSlavchovUX** [comment]
Hi @Lukeybooi i see your point above and you are absolutely right. Thank you for pointing that out and I will close this ticket.
