### ISSUE TITLE
Table links font size smaller than other fields

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1455]
I was unable to find the exact sizing used through the inspection tool but you can visibly see the sizing on any text with a link is smaller than text anywhere else on the table. 

Can we kindly ensure that link font sizing is the same as default field font sizes.
![Table links](https://github.com/shesha-io/shesha-framework/assets/153498650/4dd8deec-b139-427d-92bb-31e78df6ec78)

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, The file/Files columns are subforms rendered within the table. Are you able to adjust the text font size to be the same as default field font sizes.
