### ISSUE TITLE
On permission select, clear out the characters used when searching

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1458]
In a scenario where a user searches for a permission before selecting it, after making a selection, the characters used for the search remain visible in the field, even after moving away from it and re-visit the field. The only ways to clear the characters are either by manually removing them or by clicking the component again to clear them out. Unlike autocomplete and dropdown, which automatically clear out upon value selection

**Steps to reproduce the behavior:**
1. Drag and drop `permission autocomplete` component
2. Click on the component and search for a permission
3. Select the searched permission and check the characters used for searching on the component
4. Move you cursor outside the component then select the component again
5. Actual Results: The characters used when searching are still showing

**Expected behavior**
The same behaviour used on autocomplete and dropdown should be applied on this component whereby upon selection after searching, it should clear out the characters

See attached video

Uploading Recording 2024-05-06 144510.mp4…

**Comment by hlayisanimazuze** [comment]
Related item
#693

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze 

I specifically added this behavior because, unlike autocomplete and dropdown, you can select several items at the same time using checkboxes

You can press Escape key to clear search text
