### ISSUE TITLE
Template dynamic values not passed to new form creation

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1471]
When a template form has dynamic values configured, upon new form creation the dynamic values configured from the template are not displaying on the new form

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=b2353d28-4d4f-4280-a19d-c794a2e29f3f' template
2. Click on button group component and navigate to  'dynamic values' 
3. Click on additional properties and double check the values provided
4. Navigate to: https://function-adminportal-test.shesha.dev/dynamic/shesha/forms and create a new details form 
5. Upon creation you will be navigated to the details view and click on 'button group' component and navigate to dynamic values button
6. Click on additional properties and confirm the dynamic values provided
7. Actual result: The dynamic values configured on the template, are not passed down to the new form created

**Expected behavior**
The dynamic values configured should be the exact way configured on the template when viewed on the new form created

Template example
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/84ed121b-feeb-4015-a075-a5dbc28f2f11)

New form created based on the template
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/9f59794d-9de4-4ff1-93af-13d71e452348)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, the behaviour is still the same: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=c7fa5755-1ba7-4469-9f2d-fd312d043d32

It still doesn't append the dynamic values configurations. I deleted the initial button I had, reconfigure a new one then create a new form and it still doesn't come with the dynamic values
