### ISSUE TITLE
Components do not adhere to the permissions specified

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1497]
This card will list components accessible to users without configured permissions
- Button Group: The main permission property available for the entire button group. The permission inside the button group works accordingly
- Validation errors
- DataTable: The main permission property available for the entire dataTable. The one for columns works accordingly
- Quick Search
- Divider
- JS option: We returned array of the permissions and it was not working

**Comment by AlexStepantsov** [comment]
Validation errors and Divider should not have Permission setting
All other fixed
