### ISSUE TITLE
Form `Edit Mode` update

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1517]
- Combine Edit Mode and View Form Info features into one toggle
- In the sidebar, move the clickhandler from the entire sidebar, to just the Edit Button
- Only show Form Info when the user hovers over a specific form and hide it when the user's mouse leaves the form, except when Edit Mode is turned on initially, in which case the Form Info will disappear after 3 seconds unless the user moves the mouse away from the set form.
- Closing the Form Info should exit the Application Edit Mode
- Clicking on the Pencil Icon should open the selected form in the Form Designer pop-up

**Comment by Tshepiso-R** [comment]
The UI is still under review, and we will create a card that includes the latest updates to the design.
