### ISSUE TITLE
If setFormData is used `onInitialized`, the value does not get appended onto the specified field in the form

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1519]
If you set a value onInitialized and update a field with that, the value does not get appended onto the specified field in the form. Example: If you set an email address and you want the value to be appended when the form loads, it does not
```
setFormData({
  values: {
    emailAddress1: "admin@gmail.com",
  },
  mergeValues: true,
})
```
Repro steps
1. Navigate to the designer form: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=3e89038f-7998-44b5-a6af-e6ee9531d853
2. Click on settings and click onInitlaized
3. Check the setform data script added
4. Click on and check emailaddress field
5. Actual Results: The email address written onInitialized shows
6. Navigate to: https://function-adminportal-test.shesha.dev/dynamic/testModule/mayMonday-table
7. Click on 'Add' button
8. Check email address
9. Actual Results: The field is empty

Expected Results:
The value written should get appended onto the specified field in the form

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, with the latest changes, this issue is still occurring. Use this link: https://function-adminportal-test.shesha.dev/dynamic/TestModule/parentForm-table
-Click on the 'Add' button
-Check email field
-The value set onInitialized is not appended


NB: When use it on the details view it is view, the issue is when you use setFormData on a dialog view

Check the configurations:  https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=e1244645-ca5f-4c23-8a25-9685f9867c3f, the value shows on the designer mode

**Comment by AlexStepantsov** [comment]
No longer relevant due to #1634.

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's implemented.  
To set form fields data you can use **form.setFieldValue** or **form.setFieldsValue** in one of new event handlers (depends on the required logic):
- onBeforeDataLoad - fires after initialization of the form but before loading of the data
- onAfterDataLoad - fires after data loading. This event should be used for most of use-cases.
