### ISSUE TITLE
Get `/api/StoredFile/StoredFile/{fileId}/Versions` displays a 500 error

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1522]
A file component allows a user to view the history of the uploaded file. When you hover on the history icon, the endpoint fails. The same error gets thrown on swagger

**Steps to reproduce the behavior:**
1. Go to 'https://function-api-test.shesha.dev/swagger/index.html?urls.primaryName=StoredFile'
2. Click on 'GET /api/StoredFile/StoredFile/{fileId}/Versions'
3. Enter file id: 1ccdbfb7-85dc-4607-b80e-5c7cc8efac59
4. Click on 'execute'
5. Actual Results: 
```
{
  "result": null,
  "targetUrl": null,
  "success": false,
  "error": {
    "code": 0,
    "message": "An internal error occurred during your request!",
    "details": "Error mapping types.\n\nMapping types:\nList`1 -> List`1\nSystem.Collections.Generic.List`1[[Shesha.Domain.StoredFileVersion, Shesha.Framework, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Shesha.StoredFiles.Dto.StoredFileVersionInfoDto, Shesha.Application, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]",
    "validationErrors": null
  },
  "unAuthorizedRequest": false,
  "__abp": true
}

```
**Expected behavior**
The file version should be retrieved successfully

Confirm if it is pulling correctly on: https://function-adminportal-test.shesha.dev/dynamic/TestModule/updateTable-details?id=e2c8610a-f4a0-4624-82a7-042a909c2b38. Click on 'history' icon on the file uploaded

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
