### ISSUE TITLE
Migrations fail on PostgreSql

### ISSUE THREAD

**Issue by IvanIlyichev** [shesha-io/shesha-framework#1531]
**Describe the bug**
The migration process fails due to incorrect sql syntax.

**To Reproduce**
1. Set database type as PostgreSql, set the connection string.
2. Run the application
3. See error

**Expected behavior**
Application starts without errors.

**Additional context**
List of migrations to fix:

- M20240502101400
- M20240501134700
- M20240501141100
- M20240502101000
- M20240506113900

**Comment by hlayisanimazuze** [comment]
We encountered an issue while testing this item. The migration issue we encountered is mentioned on this item #1632. Therefore, I am adding this item to the backlog until the issue is resolved. This will allow us to close the release 35 sprint 2
