### ISSUE TITLE
Hydration Error when running Shesha on LocalHost

### ISSUE THREAD

**Issue by OmolemoBlessingLethuloe** [shesha-io/shesha-framework#1561]
**Describe the bug**
Hydration Error occurs when you run Shesha on localhost and keeps appearing when you refresh.

**To Reproduce**
1. Run frontend Shesha solution / refresh localhost Shesha solution

**Expected behavior**
The error should not occur

**Screenshots**
![image](https://github.com/shesha-io/shesha-framework/assets/82062654/e6418f81-063f-4dac-a0e5-bbe1d32041e4)

**Additional context**
It becomes distracting and unappealing when people are developing on their local - there is a higher chance that external people will see this as bad sign.

**Comment by teboho** [comment]
This issue is no longer occuring

**Comment by teboho** [comment]
Screen recording

https://github.com/user-attachments/assets/92a39a55-7c67-4435-982f-c654723dadf0
