### ISSUE TITLE
All entities listed in Entity Configuration include 'six' in the label name

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1585]
**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/settings/entity-configs/configurator'
2. Browse all the entities listed on the component
3. Actual Results: All the entities include 'six' on the label and from the general tab the label name does not include 'six', including the entity getting called from the frontend/swagger

**Expected behavior**
Remove the 'six' from the list of the entities

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/acf7771a-cd58-4331-a85f-e2040680baa3)

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi @James-Baloyi, please check this issue, there might be someone who forgot to remove the text when debugging. There's no where I can locate that 'six' from the endpoint

**Comment by hlayisanimazuze** [comment]
Related item
#1460

**Comment by James-Baloyi** [comment]
@hlayisanimazuze fixed and PRed
