### ISSUE TITLE
Custom endpoint returns an int instead of the referenceList item name

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1616]
If the endpoint has a referenceList item, when rendered, it shows an int instead of referenceList item name

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/in-line-editing-details?id=b7f0594e-9a6b-478d-bf35-e71962070507'
2. Scroll down to the second panel and check the last column
3. Check the value displayed
4. Actual Results: The reference List column displays int instead of the referenceList item name

**Expected behavior**
When a custom endpoint is rendered, it should be able to display the referenceList item name instead of int from the UI

NB: Please also check on a get if it works correct, I don't have a get endpoint

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/4644e2d2-12c3-498b-9aa3-81d2fdd55c16)

**Comment by AlexStepantsov** [comment]
DynamicDto is always send RefList as an integer value. Proper handling of this value must be done on the client/form side.

Usually the table has metadata of the Entity it works with and automatically configures the column. For custom Endpoints, you need to configure the column. For example, use Dropdown to display a column.

I added the ability to configure Dropdowns for columns.

Note: For tables configured to work with Entity, the Dropdown setting will always be reset to the Entity metadata to avoid data inconsistencies
