### ISSUE TITLE
If an item is dragged and dropped outside a group, the dropped item disappears from the list

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1618]
If a group has items inside, when dragging and dropping those items outside the group, the dropped item disappears

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/'
2. Click on 'edit' mode and click on the side menu/use a button a group
3. Look for a group that has items
4. Click on the item inside and drag it outside
5. Actual Results: After dragging the item, it disappears from the list

**Expected behavior**
The item should be located exactly where it was dropped. NB: This should be fixed globally

https://github.com/shesha-io/shesha-framework/assets/151041759/94b739be-33be-4f56-bbcb-012912131258

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
