### ISSUE TITLE
If a table has a column that renders multiple referenceList, the export to excel endpoint fails

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1624]
When a table has a column that support multiple values, upon exporting to excel, the endpoint fails, however when you remove the column and export again, it will be successful.

**Steps to reproduce the behavior:**
1. Go to 'https://pd-dispatcher-adminportal-test.shesha.dev/dynamic/Boxfusion.Ems/EmsDispatchTeam-Table'
2. Open developer console and elmah
3. Click on 'Export'
4. Actual Results: The endpoint fails, displays a 500 error: `Unable to cast object of type 'System.Object[]' to type 'System.IConvertible'`
5. If you remove skill type column, the endpoint export successfully

**Expected behavior**
If a column has a multi-value, when exporting to excel, it should export successfully

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/8eaa07c9-8122-4fc8-9d77-ac88f67397b4)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, I will list all possible reasons I receive from the team here:
- If an entity has specifications implemented

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Please provide an url of the example. I think there is a bug in the specification and the reason is not on the framework level

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , should I close this item? I will create a new one when the team reports a new issue against the export functionality

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Yes, you can close it
