### ISSUE TITLE
RichTextEditor component displays value on top of placeholder text when rendered in a edit dialog

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1656]
**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/testRich-table'
2. Click on 'edit' pencil of any record on the table
3. Upon displaying the dialog, check the value displayed on the richTextEditor component
4. Actual Results: The value is not clearly visible due to the placeholder text showing while there's a value

**Expected behavior**
If a placeholder is specified, upon rendering, if the component has a value, the placeholder should not show. The placeholder only shows when the component is empty. See details view: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/employee-text-details?id=da78f30f-2afe-4f94-9c8b-03f4f3978ead

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/d1b020b2-7821-47a2-8197-a8987ffdefc3)

**Comment by hlayisanimazuze** [comment]
Related Item
#984

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
