### ISSUE TITLE
Add mobile option on the display layout options

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1665]
<img width="1366" alt="Image - 2024-06-07T184351 664" src="https://github.com/shesha-io/shesha-framework/assets/151041759/d5c6c85c-be70-4361-a35e-5fd35d5b65c0">

**Comment by Tshepiso-R** [comment]
@nthangeniphumudzo

The devices duplicate when you attempt to scroll and some devices disappear
![image](https://github.com/user-attachments/assets/afdcea8d-77e8-4541-b4ae-0358f07dbfbc)
