### ISSUE TITLE
Changes to list items in button group component do not take effect immediately

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1670]
When a button group component is configured, after adding an item/deleting within a group, the changes do not reflect immediately how it does not on the side menu. You need to navigate to a different button/group for the update to take effect. This is only affecting the buttonGroup component, any component referencing the grouping such as side menu it is fine

**Steps to reproduce the behavior:**
1. On any form, drag and drop a buttonGroup component 
2. Click on the component and click on 'Add Group' option
3. After adding the group, click on 'Add item' within the group
4. Hover below the new item added and click on the 'Add' pop-up
5. Actual Results: The button does not reflect
6. Click on the button group
7. Actual Results: The item added within the group shows
8. Click on delete icon on the previous button added
9. Actual Results: The button still shows
10. Click on the group item
11. Actual Results: The item got removed

**Expected behavior**
The change should take effect immediately

https://github.com/shesha-io/shesha-framework/assets/151041759/ed25f9fd-d7b4-43f9-a568-bacb825a6544

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Will be included as part of release 35
