### ISSUE TITLE
Updated query parameter values are not saved in action configurations

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1678]
**Bug Description:**
When configuring action properties such as Navigation, Show Dialog, and API Call, a query parameter is required in some use cases. When entering the parameter in properties such as query string parameters, additional properties, and parameters on components like buttons or button groups, updating any previously saved value is not successful. Users must delete the old value/parameter before entering an updated one. This issue occurs universally wherever the button or button group component is utilized

**Steps to Reproduce:**
1. Navigate to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/bugtable-fix050624'.
2. Open the form designer.
3. Select the button group component.
4. Click on 'Customize Button Group'.
5. Select the button labeled 'Navigate to Details'.
6. In the action configuration panel, click on 'Parameters'.
7. Update any value in the parameters.
8. Save the changes.
9. Refresh the form designer.
10. Repeat steps 3 to 7.
11. **Actual Results:** The updated value does not persist and the previous configuration remains. To apply changes, you must delete the entire item and recreate it.

**Expected Behavior:**
When updating values in the action configuration properties (including Query String Parameter, additional properties, and parameters), the newly updated values should be saved and retained upon refreshing the form designer.

**Additional Information:**
- This issue is consistent and reproducible across various instances of the button or button group component.
- The problem impacts user workflow by requiring redundant deletions and recreations of configuration items to apply changes.

https://github.com/shesha-io/shesha-framework/assets/151129946/32741b49-7582-4bc8-bd96-762cb34520b5

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
