### ISSUE TITLE
Table Columns Bold By Default

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1687]
Can we kindly set all table columns to be bold by default. This is the general norm to create a visual hierarchy between the table and the information within it. Ant design uses bold table columns for their default components.

![TableHeadings](https://github.com/shesha-io/shesha-framework/assets/153498650/83cf4e35-8823-437c-bab6-16c1e437864a)

**Comment by Tshepiso-R** [comment]
Hi @nthangeniphumudzo , could you please reduce the font weight to 600? The current implementation feels a bit too heavy. We’ve consulted with @AlexanderSlavchovUX , and he also recommended scaling it back to 600.
