### ISSUE TITLE
Table view selector does not save updated changes

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1690]
Example: If filtering query is provided and save successfully, upon updating the same query, the changes are not saved successfully. A user requires to delete the filter and re-configure. Example: https://function-v0-35-adminportal-test.shesha.dev/shesha/forms-designer?id=e04df1e0-0696-437f-be59-90cf5cd730b9

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/login' and navigate to any form designer
2. From the builder widgets, drag and drop `tableviewselector` component
3. Add a new filter
4. Configure the filter and save your changes
5. Click the big Save button to save the configurations 
6. Refresh and navigate back to the filter
7. Update anything from the query/filter and save the change
8. Click the big Save button to save the configurations 
9. Refresh the page and navigate back to the filter configurations
10. Confirm if the changes are updated
11. Actual Results: The changes are not saved

**Expected behavior**
If the configurations are updated, it should save successfully

**Comment by hlayisanimazuze** [comment]
Related #1678

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
