### ISSUE TITLE
Error displayed when selecting date/time property on filter

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1706]
Upon selecting a date/datetime or time property on any filter property such as permanent filter within dataTablecontext or tableview selector,` An error has occured e[t] is not a function` message gets displayed. 

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=ae71ad60-ebf7-4fd7-b26f-f2d628f69daf'
2. Click on 'tableviewselector/dataTabecontext' component
3. Depending on the option selected, navigate to configure filter/query builder
4. Hover on the query builder configs and click on 'Add rule'
5. From the properties dropdown, search for a date/time/datetime property and select it
6. Actual Results: Upon selecting, ,` An error has occured e[t] is not a function` message gets displayed

**Expected behavior**
Upon selecting the property, the component should not crash

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/0478c799-1cc4-4e27-b602-f87b61fb20b0)

**Comment by hlayisanimazuze** [comment]
Related Issues #1690

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
