### ISSUE TITLE
Allow viewing of the latest configurations without publishing the form

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1712]
Currently, public portal only allows a published form to be viewed. It should be possible for a user to view the latest changes without publishing the form

**Comment by hlayisanimazuze** [comment]
Related Item
#1174

**Comment by Tshepiso-R** [comment]
Hey @Lukeybooi Please note that this is still not resolved. Find the screenshots below
![image](https://github.com/user-attachments/assets/3c94110b-a21b-455b-a9b7-874af99def11)
![image](https://github.com/user-attachments/assets/982fd746-ad90-4d32-879c-995e2de12a1d)
