### ISSUE TITLE
Prepared values data logs an empty obejct

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1713]
Creation of the new form got broken due to the data script used whereby the data is logged as an empty object. If you console data anywhere on prepared values, it comes out as an empty object

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/shesha/forms'
2. Open developer console
3. Click on 'Create New'
4. Enter all the details and click on 'Ok'
5. Check the object logged
6. Actual Results: The data is not logged and this results to the creation of form not working as expected

**Expected behavior**
The data object should log the required data

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, I'm unable to edit any details view. Please check if this issue is related to the current item and ensure the solution allows editing. If it doesn't resolve the issue, I'll create a new card

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Both issues are fixed, please check
