### ISSUE TITLE
Wizard step navigation does not update component configurations

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1714]
When navigating between steps in a wizard, the component configurations do not update correctly. For example, if step 1 has certain components configured and step 2 has different components configured, upon navigating from step 1 to step 2, the configurations displayed are still those of step

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/updated-table'
2. Click on 'Wizard' button
3. Check the configurations on step 1
4. From the dialog, click on 'Next' button
5. Double check the configurations displaying on step 2
6. Actual Results: The configurations are not updated

**Expected behavior**
Upon clicking next, the configurations of the next step should be updated and display according to the wizard configurations

https://github.com/shesha-io/shesha-framework/assets/151041759/7e69028e-c16a-496e-9c5e-47f7c3cbdead

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
