### ISSUE TITLE
Custom render subform in dataTable column not displayed in read mode

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1717]
If a display form is configured, the subform does not display when the table is rendered in read mode. However, the subform displays correctly in create or edit mode

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=2e6ea205-209c-4e28-9578-86f86618a7b3'
2. Check the child table displayed
3. Actual Results: The data is not displaying, however it shows that the table has data
4. Click on the edit pencil
5. The configs from the subform rendered shows
6. Click on reset icon to close the edit mode
7. Actual Results: The same subform displaying on create or edit is used, however on display the subform does not show

**Expected behavior**
The subform configurations should display as expected

Actual Results
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/981e379f-1b1c-4f3e-aee9-fd6946ebc5cb)

Expected Results (NB: This is from a different branch)
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3035da5a-60b7-4cac-9216-74aab051aaf2)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
