### ISSUE TITLE
Upon selecting an entity from the entity configuration, the entity information does not display

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1720]
For example: If member entity is selected on Entity Configuration view, upon selecting, the relevant information of the entity does not display such as properties, general info and views

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/settings/entity-configs/configurator'
2. Search for 'member'
3. Click on the 'member'
4. Upon clicking on the entity, check on general, properties and views tab
5. Actual Results: All tabs are blank. The relevant information does not get displayed

**Expected behavior**
Upon selecting the entity, the relevant general, properties and views related to the entity should display

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/9ee62f5d-743b-4cf7-9803-7d6a9a37c023)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/d9556616-a836-444f-b0f0-d8245446dc8d)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/6587f1f7-cdb9-43ea-a91e-e80ad9226975)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
