### ISSUE TITLE
Upon selecting an service or endpoint from the permission object/permissions, the relevant information/configs do not display

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1721]
Example: If an endpoint is selected, there are two containers that get triggered based on the data available. Upon selecting the service or endpoint, data variable logs an empty object which results to the configurations specified not working.

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Shesha/permissioned-objects'/https://function-adminportal-test.shesha.dev/dynamic/Shesha/permission-configurator
2. Click on 'service/endpoint'
3. Upon selecting, check on right hand side to see if the relevant configurations show
4. Actual Results: No relevant information gets displayed because the data object logs empty

**Expected behavior**
Upon selecting, the relevant configurations should display

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/b2ecc3e9-c3f5-4c70-9e8a-1a764c448278)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
