### ISSUE TITLE
The save button does not automatically refresh after an action has been performed

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1723]
When saving and setting a form to ready or publishing the form, the form does not auto-refresh to update the status accordingly. A manual refresh is required to see the updated status

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/shesha/forms'
2. Click on the third icon to any form that is in draft status
3. From designer view of the form, top right, click on the dropdown on the save button
4. Click on 'Save and set ready' option
5. Upon clicking the option, a toast message will get displayed, however the form is still in draft
6. Refresh the form and the form will be updated accordingly
7. Click on 'publish'
8.  Upon clicking the option, a toast message will get displayed, however the form is still in ready
9. Refresh the form and the form will be updated accordingly
10. Actual Results: The form does not auto-refresh to update the status accordingly

**Expected behavior**
Upon clicking the save and ready, or publish, it should auto-refresh 

See attached video

https://github.com/shesha-io/shesha-framework/assets/151041759/22e6674f-3ec6-48a5-b821-f1e3332265ef

**Comment by hlayisanimazuze** [comment]
@IvanIlyichev, this is also affecting the quick edit configurations, it does not auto-refresh. You have to manually refresh. Example: 
https://function-adminportal-test.shesha.dev/dynamic/Shesha/mobileTest-table, click on the add button, click on the link to navigate to the designer of the form, update a text and click on save

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
