### ISSUE TITLE
Components that does not respond the first time a user pastes

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1728]
- RichhtextEditor: When 'ask before paste HTML/ask before paste from Word/Excel' is set to true, when a user paste, the component does not respond the first time a user pastes
- TableViewselector/permanent filter: upon click 'Add rule/add group', the component only respond the second time a user clicks it

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/richTest-table'
2. Click on 'add'
3. Copy any information on the browser (lorem)/word document
4. From the richTexteditor component, click on it then paste the information copied
5. Actual Results: The first time a user pastes, the component does not respond. It only responds the second time a user paste

**Expected behavior**
Upon clicking paste controls, the component should respond the first time a user paste.
Upon clicking add rule/addgroup when applying a filter on the tableViewselector/permanent filter, the component should should respond accordingly

A place where it is working as expecte: https://function-v0-35-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/employee-text-table

This warning only gets displayed the first time addnewrule/add groupclicked and not respond
<img width="935" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/31b76568-5378-4ab4-9f90-77c46605eaea">

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
