### ISSUE TITLE
Navigation link on hover should appear only on action configurations set to navigate

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1731]
Example: When a button is configured to display a dialog, hovering over the button incorrectly shows the closest available URL. e.g., if the button is rendered on the details view, hovering over it will display the details view URL. Similarly, in the side menu, it shows the previous URL clicked

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/navupdate-details'
2. Hover on the edit or audit log option and check at the bottom of the page
3. Actual Results: a url gets displayed while the configurations are using a different action

**Expected behavior**
The navigation url should only display on navigation configurations

https://github.com/shesha-io/shesha-framework/assets/151041759/739abd8b-86c8-49df-91a7-0b1eb4fccbaf

**Comment by hlayisanimazuze** [comment]
Related item #1326

**Comment by James-Baloyi** [comment]
@hlayisanimazuze the issue where a non-navigation action item icon appears as black instead of the primary colour has been fixed in this PR: https://github.com/shesha-io/shesha-framework/pull/1786

**Comment by James-Baloyi** [comment]
@hlayisanimazuze the bug has been addressed.
