### ISSUE TITLE
Adding new initialization loader

### ISSUE THREAD

**Issue by OmolemoBlessingLethuloe** [shesha-io/shesha-framework#1765]
Replace the old initialization loader with a new modern one from the UX team

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe , @Tshepo1103-lab, the below screenshot is what I'm seeing on function site and I believe this is not the expected results. Please update and set the ready for testing when it is complete

![image - 2024-06-28T091116 322](https://github.com/shesha-io/shesha-framework/assets/151041759/ad65ca9d-0c70-4e14-b245-c916d8b5fe15)
