### ISSUE TITLE
View Type Reset on page load

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1768]
**Describe the bug**
On page load, the view type resets to "Live" and the "Show Form Info" setting resets to false.

**To Reproduce**
Steps to Reproduce:

1. Navigate to "https://function-adminportal-test.shesha.dev/dynamic/Shesha/bug-fixes?id=8b56ffc6-91b8-4910-824e-03266fe790aa"
2. Change the view type to "LATEST
3. Enable the "Show Form Info".
4. Refresh the page.

** Expected Result:**
The view type should remain as selected, and the "Show Form Info" setting should stay enabled.

Actual Result:
On page load, the view type resets to "Live" and the "Show Form Info" setting resets to false.

Screenshots/Video:
https://www.awesomescreenshot.com/video/29030762?key=3cb2a12c0f31f6395f57f19d060c3ef1

**Comment by teboho** [comment]
Potential cause https://github.com/shesha-io/shesha-framework/pull/1763
