### ISSUE TITLE
Inconsistent primary color application across the components

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1769]
**Describe the bug**
Initially, all the buttons and links on the system inherited the primary color. However, they now appear blue. This issue is also observed in the following places:
- When hovering over some input fields, such as Dropdown, Checkbox, Checkbox Group, Radio, Autocomplete, Color Picker, Entity Picker, and Child Entity Tag Group
- The selected date and today's date on the date field's calendar (this also applies to the time picker)
- Info alerts appear bluey
- The "Press to select" options for Image, File, and File List
- Wizard step numbers and buttons
- When rendering autocomplete with "use quickview" set to true and entity reference
- When configuring `message.info` in the code editor or in the action configurations, the color displayed does not correspond to the info color

**Expected Results**

- All buttons and links should inherit the primary color as defined by the system's theme.
- When hovering over input fields (Dropdown, Checkbox, Checkbox Group, Radio, Autocomplete, Color Picker, Entity Picker, Child Entity Tag Group), the hover color should match the primary theme color.
- The selected date and today's date on the date field's calendar (and the time picker) should use the primary theme color.
- Info alerts should reflect the color defined for info alerts in the Theme.
- The "Press to select" options for Image, File, and File List should use the primary theme color.
- Wizard step numbers and buttons should display in the primary theme color.
- When rendering autocomplete with "use quickview" set to true and entity reference, the colors should match the primary theme color.
- When configuring `message.info` in the code editor or action configurations, the displayed color should correspond to the info color defined in the Theme

**Please note that we might have missed some places, please ensure that this is resolved globally**

**Screenshots**
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/9a15894b-eed0-4ed9-978e-0412905acbe7)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/23accc47-e5bf-42ec-b83f-7cf86b072a8d)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/60004fc6-4bb0-4bec-aafd-3e5bebccd42d)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/e33e442a-6392-4e43-a160-0e461a449d20)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/4f97c823-d323-40a0-8ae7-e6480807258c)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/ee3f09f3-29db-4dcf-a35b-92c87ab1676d)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/aef3dfea-4d19-4828-8534-b6dc22dcc2dd)

**Comment by hlayisanimazuze** [comment]
Potential cause https://github.com/shesha-io/shesha-framework/pull/1763
