### ISSUE TITLE
Side menu does not inherit form/view level permissions when 'navigation URL' is used

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1808]
With the current implementation, the side menu does not seem to inherit from the view/form level permissions when the permissions are specified on the view/form level while the navigation option used is url. Example: https://function-adminportal-test.shesha.dev/dynamic/TestModule/anony-table

Login as: `loginT `and password: (the default password we use on function)

- From the side menu, scroll down and click Permissions menu item
- Upon clicking, the form will display 'Sorry, you are not authorized to access this page' to show that the user does not have the required permissions, however the side menu still shows
- Expected Results: When the side menu inherits from the view/form level, upon logging in, it should check the permissions assigned to the current user logged in and hide/show the side menu item accordingly 

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a1af709e-3dbc-46ef-ae32-1cbe5e5f2ffa)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/c1b3070c-b050-4569-90c6-c10a5886116b)

**Comment by hlayisanimazuze** [comment]
Related item #711

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze 

Form permissions checked only for Form navigation mode

This menu item configured as Url navigation
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/24a5de2d-4237-4a10-bcdb-b64c160242e0)

For example the next menu item is configured as Form navigtion and hidden from the menu for the LoginT user
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/08eff3e6-8df5-4709-beb8-2cefbc49ecf2)

**Comment by hlayisanimazuze** [comment]
@AlexStepantsov, Navigation mode supports two options: url and form, is it not possible to support both modes?

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze 
Url mode means that any URL can be specified, not just a link to the form. This makes it difficult to determine permissions.
We can add Url parsing to get form Id if there is a `/dynamic/` part in the Url, but it looks like extra work, considering that there is a navigation mode specifically for forms

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, I spoke to Ian and he agrees with supporting the form mode option only
