### ISSUE TITLE
Newly Created Table view component - add item model is not closeable by default

### ISSUE THREAD

**Issue by MarshallRJ** [shesha-io/shesha-framework#1810]
When adding a new table view configuration. if during the configuration the "add" button is clicked while configuring the layout (eg: unintentionally while moving components around). The add new recode model will display. There is no way to close this model (since no hooks have been defined) and thus no way to navigate away. The only way back is to refresh (F5) the screen.

**To Reproduce**
1. In Admin portal Click Configurations->Forms
3. Click Create new form
4. Use the table view form and bind to entity Shesha.Domain.Persons
5. Once in the form editor click on the "add" button
6. The add new record modal will display but closing it with X or Cancel button does not close the model

**Expected behavior**
Clicking the Model with X or Cancel Button should close the model and allow the user to continue editing the table view form

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version Shesha.Framwork 0.35

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, this is not resolved: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=acea486e-5f0f-4064-9b3c-8067f373d91d. I've created a new table form and it is still behaving as mentioned above.
