### ISSUE TITLE
Section Separator clean up

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1826]
1. All existing configurations, the label is right aligned
2. There's no bottom padding on render
3. Font color: Does not have the 'clear' option, like how line color is
4. When a font size configuration is removed, currently it removes the text, shouldn't it reverts to the original size you get when you drag and drop the component? (refer to how line width responds upon clearing out the width configuration)
5. If inline and dashed properties are set to true, while line thickness is empty, the component lines becomes out of shape
6. If inline is set to true, while line thickness is empty, the line disappears however when inline is set to false the line shows even when the line thickness is empty. Shouldn't the behaviour be same?
7. How does 'no margin' works?
8. The tooltip is not aligned properly with the text: https://function-v0-35-adminportal-test.shesha.dev/dynamic/TestModule/CRUD-table1

Form: https://function-adminportal-test.shesha.dev/dynamic/TestModule/uitest-form

Designer: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=cdb93f8d-801a-4e03-8c50-a84cf1534f19

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/d2cb134d-29a0-472b-983d-1cd807ef9246)
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/021d267e-843c-453d-8888-efcd1c599727)
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/cd82a6b8-9ede-4793-97ee-e32bb998cdad)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/2522529a-28e7-4547-9a31-aa89851bb7d1)

**Comment by hlayisanimazuze** [comment]
Related Item #1741

**Comment by Tshepiso-R** [comment]
1. When you increase Line Thickness, the line only grows downwards.
2. When the inline is true and the label is hidden, the component leaves a gap between the lines

![image](https://github.com/user-attachments/assets/ffe9e7e5-b3b9-44a4-9eb2-a0e471585d43)
![image](https://github.com/user-attachments/assets/afef7af4-294b-4e9e-b125-97f8c2b7a61f)
