### ISSUE TITLE
VB.NET Support

### ISSUE THREAD

**Issue by InteXX** [shesha-io/shesha-framework#1848]
How difficult would it be to have this tool generate VB.NET code in addition to C#?

**Comment by ihouvet** [comment]
Hi @InteXX - Thanks for your interest in the Shesha project! The core team doesn’t have any immediate plans to support VB.NET.
A point of correction however, the tool doesn’t generate code. You develop on top of the Shesha libraries which being .NET Core based you can do in C#, VB.NET or any other .NET supported languages.
To support VB.NET developers therefore the main work required would be simply to convert the starter project (currently based on C#) to VB.NET which although not trivial is not an enormous piece of work for an experienced VB.NET developer.
Though the core team doesn’t have capacity for this we would certainly welcome any contributors who wish to assist with this.
Let us know if you would be tempted to contribute in that way and will be happy to have further discussions and provide additional guidance :)

**Comment by InteXX** [comment]
Hm, interesting.

Certainly, I'd be happy to do a one-off conversion of the current C# starter project to VB.NET.

Could you point me in the right direction?

**Comment by ihouvet** [comment]
Hi @InteXX - Apologies for the delayed response but if you are still interested (which would be very cool :).
1. Create a VB.NET version of the existing C# starter project template under /shesha-starter/backend in a new folder e.g. /shesha-starter/backend-vb
2. Submit the PR so we can review and merge
3. We will then update the [Get Started with Shesha](https://www.shesha.io/get-started-with-shesha) page to allow a VB.NET option to be downloaded

**Comment by InteXX** [comment]
> Apologies for the delayed response

Not to worry... there's plenty to do around here! 

I'll work on this today.
