### ISSUE TITLE
StoredFile image not displayed as background in container component

### ISSUE THREAD

**Issue by miracleMa** [shesha-io/shesha-framework#1861]
**Describe the bug:**
The stored file image is not working properly when used as a background on the container component, but it works fine when used on the image component. When entering the storedFile ID, the image is not instantly pulled for the background.

**To Reproduce:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/Backgroud'
2. Click on the container to view its properties
3. Scroll down to Background. 
4. On the background type dropdown, select "image"
5. On the image source type drop-down, select "storedFile"
6.  Enter the storedFile ID (E.g 97621427-1517-4974-892e-59b9851c8503)

**Actual Results:**
The background image is not displayed on the container after entering the storedFile id.

**Expected Behavior:**
The background image should be displayed on the container when using a storedFile image source type. The behavior should be the same as the image component.  Upon entering the storedFile ID the image must be pulled instantly.

**Screenshots:**
![image](https://github.com/user-attachments/assets/7740b45f-748d-4287-a35a-44a703f47b1e)
![image](https://github.com/user-attachments/assets/b0fc5fb7-10ea-4dc2-836c-8503e257142b)

**Comment by Tshepiso-R** [comment]
Related to #1789
