### ISSUE TITLE
`UseAuthActions must be used within an AuthProvider` error gets displayed when accessing no-auth pages

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1870]
Example: When you access forgot password from login, the pages use no-auth and this results to the page breaking due to this error:  `useAuthActions must be used within a AuthProvider`

**Steps to reproduce the behavior**
1. Go to 'https://function-adminportal-test.shesha.dev/'
2. Open developer console
3. Click on 'forgot password' link
4. Check error displaying on console
5. Actual Results: The page breaks and `useAuthActions must be used within a AuthProvider` gets displayed

**Expected behavior**
The no-auth implementation should work as expected

**Comment by Tshepiso-R** [comment]
The error is no longer showing
![image](https://github.com/user-attachments/assets/e7553db1-617f-4419-b31c-79f45456edc2)

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, with the latest changes, this issue got re-introduced again. https://function-adminportal-test.shesha.dev/no-auth/shesha/forgot-password?mode=edit

![Uploading image.png…]()
