### ISSUE TITLE
The application initially displays a default color before switching to the actual primary theme color 

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1871]
Upon loading the page, a default color gets displayed before displaying the application's theme color

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/login'
2. Login
3. Check the initial color getting displayed when moving across any page example: the loader color, login button
4. Actual Results: 

**Expected behavior**
The application should immediately display the primary theme color upon page load without showing the default color first

Example: The fetching form text first displays in blue, then afterwards it adjusts to the theme color
https://github.com/user-attachments/assets/371fbf73-7685-4d7a-96d0-52fe52133149

**Comment by Tshepiso-R** [comment]
Upon logging out, the application login form initially displays the primary color. After a short period, the primary color automatically changes to blue.
[function-adminportal-test.shesha.dev_login.webm](https://github.com/user-attachments/assets/cfdaafb3-7234-4db5-9aac-09355dfb53c4)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Add on release notes page

- For the loader line to inherit the primary color of the system, `app/app-provider.tsx`  is required to be added on the project level
