### ISSUE TITLE
Enhance Button Component with additional styling properties

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1877]
**Description:**
We need to enhance the Button component by adding the following properties to improve its customization and styling options. Ensure consistency with Button Group styling.

Properties to Add:
1. Width
2. Height
1. Background Color
2. Font Size
3. Font Color
4. Font Weight
5. Border (width, color, dotted, dashed)
6. Border Radius
7. Icon Position

**Additional Info:**
Check action on button and if the action URL is the same as the page URL, apply active styling.

**Comment by hlayisanimazuze** [comment]
PR
