### ISSUE TITLE
APIs should exist to store user specific settings and preferences

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1883]
### Overview
It should be possible to conveniently manage user specific settings and preferences from both the client side and the back end.

### Acceptance Criteria
1. It should be possible to define new user settings as a configuration item `UserSettingConfig`. In addition to standard properties, it should have the following properties:
   1. ClientAccess - Indicate the accessibility of this user setting from client applications: 
          - NotAccessible - Client Applications cannot access the setting. It is only used for a backend purposes.
          - Readonly - Client Applications Can read the setting, but cannot update it.
          - Full - Client Applications Can both read and update the setting.
   2. TypeName - Name of the type the setting value should be able to deserialise into.
   3. DefaultValue - that default value of the setting the first time it is accessed.
2. Back-end Api should exist allowing getting and setting of user settings
   2. Get endpoint:
      1. Parameters: moduleName, settingName, defaultValue (optional)
      2. If the setting did not already exist for the user, It should be created with the default value passed in through the endpoint. If no value was specified it should use the default value specified at the UserSettingConfig level. If no value is specified there, it should simply return empty string.
      3. Should allow specifying a setting name which isn't registered as a configuration item. It will then create the new user setting on the fly with full access.
      4. Return: value, existed (if false indicates that the setting did not previously exist.).
   4. Update endpoint:
      1. Parameters: moduleName, settingName, defaultValue (optional)
      1. Should allow specifying a setting name which isn't registered as a configuration item. It will then create the new user setting on the fly with full access.
      2. If the 'TypeName' has been specified then should attempt to deserialize into this type as form of validation prior to saving in DB.
6. Client-side api extending `user` object i.e. `user.settings` should exist
7. documentation should be updated, illustrating usage from client side and back end.

**Comment by OmolemoBlessingLethuloe** [comment]
DataType field added to SettingConfiguration entity, and DataType parameter to GET and UPDATE endpoints to substitute implementation for TypeName (like ClassName) until implementation can be reviewed.

**Comment by hlayisanimazuze** [comment]
Outstanding: Documentation
