### ISSUE TITLE
Hide form info when logged out

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1893]
**Describe the bug**
With the current implementation, when "Show Form info" is true, upon logging out login form info displays and amendments can be made while logged out.

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/'
2. Click on the 'Live' button and set "Show form info" to true
3. Logout 
4. Actual behavior** Login form info display

**Expected behavior**
Login show info should be hidden.

**Screenshots**
![image](https://github.com/user-attachments/assets/eb4702a7-76a0-4edc-8b4b-37ed1aa50012)

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi , this was fixed, it is reoccurring again and since @Lukeybooi  doesn't work on the framework anymore, please assist

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi, I've checked with the latest changes and the issue is still occurring. See attached video: https://jam.dev/c/49a0ad61-aa86-4087-bda7-072940c2dfd9
