### ISSUE TITLE
Menu does not display upon initial login until refresh

### ISSUE THREAD

**Issue by TshepisoRaganya** [shesha-io/shesha-framework#1906]
**Describe the bug**
When logging into the public portal, the menu does not display automatically. Users are required to refresh the page for the menu to appear. 

**To Reproduce**

1. Log in to the public portal. URL(https://function-publicportal-test.shesha.dev/)
2. Observe that the menu is not displayed.
3. Refresh the page.
4. Notice that the menu appears after the refresh.

**Actual Behavior**
The menu does not display until the page is refreshed.

**Expected behavior**
The menu should display automatically upon logging in without requiring a page refresh.

**Screenshot**
![image](https://github.com/user-attachments/assets/3c47e043-e64a-4bcd-b9d8-ff4a7a05a538)

![image](https://github.com/user-attachments/assets/15534838-cec7-4ea6-b13d-6df18a2ddd61)

**Comment by Tshepiso-R** [comment]
#1174
