### ISSUE TITLE
DataTable and ButtonGroup configurations require manual refresh to display

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1912]
When configuring a DataTable or ButtonGroup component, the changes do not display immediately. For example:

- Adding a new column to the DataTable and clicking the OK button does not display the new column.
- Adding a button or group to the ButtonGroup component and clicking the Save button does not display the new configuration.

The new configurations only appear after refreshing the entire page.

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=68ee0bbf-01b8-4ae3-8f49-cc693798726a'
2. Click on 'buttonGroup'
3. Scroll down to 'customise button group' on the properties panel
4. Click on add group/add new item button and update any property setting
5. Click on 'Save'
6. Actual Results: The new group/button is not displaying
7. Click 'Save' and refresh the page
8. Actual Results: The new group/button does show after the manual refresh

DataTable confirguration

1. From the above URL, click on the dataTable
2. Click on 'Configure Columns' on the properties panel
3.  Click on 'Add Column'
4. Select a property and click on 'Ok'
5. Actual Results: The new column added does not display
6. Click on 'Save' button and refresh the page
7. Actual Results: The column does show after the manual refresh

**Expected behavior**
Upon clicking Ok/Save button, the configurations should show without manual refreshing

**Comment by IvanIlyichev** [comment]
Hi @AlexStepantsov. Check your commit 1f62384db6a8f3635414ba2bb9af3d2bb2c25517 (we discussed it in PM)
