### ISSUE TITLE
Overflow options does not adjust according to available menu items when rendered

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1916]
The reason of implementing this changes: https://github.com/shesha-io/shesha-framework/issues/1740 was to accommodate screens that are smaller and can't render all the items available on the horizontal menu, however it does not render as expected

Navigate to: https://function-publicportal-test.shesha.dev/

- When any of the two overflow options are used and the zoom browser is on 100%, upon render, some of the items are not displaying example: logged in user and form status
- When a scroll option is used, it does not add the items on the scroller. Currently the scroll is static, it does not adjust the menu items and add the necessary items to scroll. Example: When my zoom browser is on 90% and the overflow option is used, the menu dropdown does show and display some of the items on the dropdown, however when a scroll option is used, it push out the form status and logged in user options
- When the screen is bigger to accommodate everything, the scroll overflow still shows. It should adjust it's visibility according to the menu items. Example:
  - If there are more items to display, the scroller should display which allows the menu items to be scrolled
  - If the menu items are few, the scroll should not show. See how the dropdown behaves 
- By default, there should be a standard spacing between the logo and the first menu item. Currently there is no spacing between the two
- Form status bar and logged in user icons are stacked when rendered on a laptop, while on a monitor it displays accordingly. It should display how it is on admin portal

Item 1
![image](https://github.com/user-attachments/assets/a4009ab2-6d4c-4134-ace7-d026993a4753)

Item 3: The last menu item available was promise Group and I would still see the scrollers
![image](https://github.com/user-attachments/assets/fedf9443-8836-4aca-a620-a3efeead1c1e)

Item 4
![image](https://github.com/user-attachments/assets/ce44d8e4-91e5-4059-9b8c-e2b681f907ee)

Item 5 (laptop screen)
![image](https://github.com/user-attachments/assets/4fe881b5-04e2-43a2-bf18-d46936273afe)

Monitor
![image](https://github.com/user-attachments/assets/bcebe9fa-7915-4dcf-b836-b158bb2251c0)

**Comment by hlayisanimazuze** [comment]
Related Item
#1174

**Comment by Lukeybooi** [comment]
@hlayisanimazuze please use the width property to resolve this issue.

**Comment by hlayisanimazuze** [comment]
Related Item: https://github.com/shesha-io/shesha-framework/issues/1948
