### ISSUE TITLE
`form:refresh` action throws error when used on stand-alone form/table

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1928]
If I set the action to refresh the form while using it on a stand-alone form/table it doesn't work example:

- https://function-adminportal-test.shesha.dev/dynamic/TestModule/form-refresh, 
- Click on the Add button and add everything then click ok. 
- Upon submitting, an error gets thrown

 
When you use it on the details view, it works accordingly example: 

- https://function-adminportal-test.shesha.dev/dynamic/TestModule/tuesdayTests-details?id=b54a5c86-0677-4fb4-9917-0caaf3ed28ac
- Click on 'Activate' button, afterwards, it will refresh the form

![image](https://github.com/user-attachments/assets/48e95a62-6d2a-4336-86ed-24df6fe3f0f6)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
This will be included on release 0.37
