### ISSUE TITLE
Deleting sub-configurations of certain components fails

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1931]
Certain components, such as DataTable, allow sub-configurations. When a column configuration is deleted and saved, the configuration does not actually get deleted.

Example of the components:
- ButtonGroup>> deleting a button/buttonGroup configuration
- ButtonGroup>> deleting a paramets
- DataTable>> deleting a column configuration
- Tabs>> deleting a tab panes configuration
- Wizard>> deleting a wizard step configuration
- Columns, KeyInformationBar and Sizable: deleting a column configuration

Example
**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=68ee0bbf-01b8-4ae3-8f49-cc693798726a'
2. Click on `dataTable`
3. Click on 'Configure Columns' on the `dataTable `properties panel
4. Hover on 'FirstName' column and click on 'delete' bin
5. Click on 'Ok' button
6. Actual Results: After the dialog pop-up closes, the column deleted still shows, even after saving and refreshing the page

**Expected behavior**
When a sub-configuration, such as a column configuration in a `dataTable`, is deleted and saved, the configuration should be removed successfully and no longer be visible

See attached video

https://github.com/user-attachments/assets/86a0505e-82a5-43bd-b4c2-20381ce5f97e

**Comment by IvanIlyichev** [comment]
Hi @AlexStepantsov. Looks like it's related to #1912
