### ISSUE TITLE
Action `Refresh table` fails when used on custom buttons

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1947]
When` action: Refresh table` is used on the action configuration while the buttonType is custom, upon executing the action, an error gets thrown `Validation failed: Action 'Refresh table' in the owner '_9Ya0XzWdoBAQpqjDkrH-S7pwUIPm5' not found.`

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/afterUpdates-details?id=828afbd7-6547-46d6-a508-0cd13df4b34c'
2. The above links has two buttons: Custom and Default. The custom one is the one throwing an error and the default one refresh accordingly
3. Click on 'Custom' button located inside panel2
4. Open developer console
5. Click on 'Custom' link on the dialog
6. Check the error getting displayed afterwards
7. Actual Results: Validation failed: Action 'Refresh table' in the owner '_9Ya0XzWdoBAQpqjDkrH-S7pwUIPm5' not found.`

**Expected behavior**
The action should be executed successfully, just how it is when using a default buttonTypes

![image](https://github.com/user-attachments/assets/e4d46f13-a664-46b9-9841-6845df367307)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
This will be included on release 0.37
