### ISSUE TITLE
UI Create New Form - Name field not visible 

### ISSUE THREAD

**Issue by ranjitsinghseera** [shesha-io/shesha-framework#1956]
Create New Form - Name field not visible in UI Side

May be this is not bug. It some configuration missing at our end. Please support.

![Error - Create New Form - Field Name not visible](https://github.com/user-attachments/assets/f2afc904-bffe-4afc-ae0c-a8257bd01022)

**Comment by teboho** [comment]
Hi @ranjitsinghseera which npm version of Shesha are using?

**Comment by ranjitsinghseera** [comment]
> Hi @ranjitsinghseera which npm version of Shesha are using?
10.8.1
![image](https://github.com/user-attachments/assets/d2c21482-197d-417e-b462-a4839ec601e8)

**Comment by ranjitsinghseera** [comment]
> > Hi @ranjitsinghseera which npm version of Shesha are using?

![image](https://github.com/user-attachments/assets/95144538-059c-40c0-a737-b64bbdca924e)

**Comment by teboho** [comment]
Alright, try to update shesha in the package.json file to version 0.36

**Comment by teboho** [comment]
> > Hi @ranjitsinghseera which npm version of Shesha are using?
> > 10.8.1
> > ![image](https://private-user-images.githubusercontent.com/158739546/355140268-d2c21482-197d-417e-b462-a4839ec601e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODcyNDMsIm5iZiI6MTcyMjg4Njk0MywicGF0aCI6Ii8xNTg3Mzk1NDYvMzU1MTQwMjY4LWQyYzIxNDgyLTE5N2QtNDE3ZS1iNDYyLWE0ODM5ZWM2MDFlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxOTQyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmNlZWMwMzBlMWJhNzUxM2NlZDA1YTM1YzM0ZjY4YzkwNGJmZDFhMmExOWNmZGIxOWFmZGZmZDViMGQ4MGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3FtOUwW4mIxNSOJRS-iGCnhsGSfCwHaSO9bLNur7kRk)

https://www.npmjs.com/package/@shesha-io/reactjs

**Comment by ranjitsinghseera** [comment]
Thank you for your quick support, We have downloaded the code again and now it is working fine.

**Comment by teboho** [comment]
> Thank you for your quick support, We have downloaded the code again and now it is working fine.

That's great to hear @ranjitsinghseera all the best with your project, reach out if you come across problems 🚀

**Comment by teboho** [comment]
@hlayisanimazuze please note that they have solved their problem
