### ISSUE TITLE
Autocomplete list not displayed on component click

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1961]
Upon clicking the component to select an entity, the view is not displayed correctly

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/shesha/forms'
2. Click on 'Create New' button
3. Click on 'Module'
4. See the way the component renders the view
5. Actual Results: The component does not display the list view as expected

**Expected behavior**
Upon clicking the component to select an entity, the view should be displayed correctly to allow users to select an entity

On first click while loading
![image](https://github.com/user-attachments/assets/cfac36a7-bc48-40bc-b6bd-8ddb069aa0d1)

After loading, this how the component displays the list
[03a7cebf-bf53-4616-9987-585a3061092b.webm](https://github.com/user-attachments/assets/83ceb35c-f655-4b98-ab34-b150f0413e26)

**Comment by hlayisanimazuze** [comment]
Possible PR that affected the list UI: https://github.com/shesha-io/shesha-framework/pull/1926

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
