### ISSUE TITLE
Base64 Image not rendering in Image component and container background property

### ISSUE THREAD

**Issue by miracleMa** [shesha-io/shesha-framework#1980]
**Describe the bug**
The Base64 property is not functioning when applied to the image component. Additionally, the image does not appear when the Base64 code is used in the container's background property.

**To Reproduce**
1. . Go to  https://function-adminportal-test.shesha.dev/dynamic/TestModule/Backgroud
2. Open the designer
3. On the image component, change the image source type to Base64 
4. Paste a base64 image code  on  " Base 64 content"

**Actual Results**
The image is not pulled. ( it shows the picture loading failure icon )

**Expected behavior**
Image must be pulled using base64 properties

**Screenshots**
![image](https://github.com/user-attachments/assets/f72ea50c-906a-40bd-a5e0-000f639c46c0)

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/member-1023'
2. Drill down to the details view.
3. Click the radio button labeled  yellow

**Actual Results**
Images using the base 64 property are not pulled  / not displayed. ( it shows the picture loading failure icon )

**Expected behavior**
The Base64 Image Source Type pulls the 3 images.

**Screenshots**
![image](https://github.com/user-attachments/assets/8def6890-be3b-40c3-83c2-3f9ba1db4112)

**Comment by hlayisanimazuze** [comment]
Related Item #https://github.com/shesha-io/shesha-framework/issues/1963
