### ISSUE TITLE
Inconsistent behavior in newly added styling properties

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1985]
1. Inconsistencies in Naming: There are inconsistencies with the names "Border Style" and "Border Type." For example, the Container component uses "Border Style," while other components use "Border Type."
2. Default Border Color: The default border color for the Autocomplete and Container components is black, while for other components, it is grey.
3. Border Width Behavior: Since the default border type is set to solid in the code, adding a border width to the Image and Container components only reflects the changes when the border type is explicitly selected. In contrast, other components respond to the border width change without requiring the border type to be selected.

**Comment by hlayisanimazuze** [comment]
PR
