### ISSUE TITLE
Image preview should render the cofigured image styles

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1989]
**Description:**
The image preview currently does not render the configured image styles correctly, especially when CSS properties such as opacity, filter, and others are applied.

**Steps to Reproduce:**
1. Go to "https://function-adminportal-test.shesha.dev/dynamic/TestModule/cards-details?id=52b58283-975c-4ddf-8781-847494182167"
2. Open the form designer
3. Drag and drop a display  image component and configure it
4. Configure Opacity and Filter
5. Save and render the form
6. Click the image to preview

**Actual Behavior:**
The preview does not reflect some or all of the configured CSS properties (e.g., opacity, filters), leading to a mismatch between the preview and the final rendered image.

**Expected Results**
Expected Behavior:
The preview should accurately render all configured image styles, matching the final output.

![image](https://github.com/user-attachments/assets/b316e9f4-2230-4134-99e1-f2f5db78ba69)

**Comment by Tshepiso-R** [comment]
related #1879

**Comment by James-Baloyi** [comment]
This item has been closed after careful consideration with the Team, as it was determined to be no longer necessary for further action.
