### ISSUE TITLE
Add shadow control to container component

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1999]
**Feature Description:**

1. Introduce a shadow effect option for the container component.
2. The shadow will have predefined styling 
3.Users can enable or disable the shadow effect through a toggle switch in the properties panel.

**Properties Panel:**

1. Add a toggle control labeled "Shadow" to the properties panel of the container component.
2. When enabled, the shadow will be applied to the container.
3. When disabled, the shadow will be removed.

**Comment by hlayisanimazuze** [comment]
PR

**Comment by hlayisanimazuze** [comment]
Further enhancements to the shadow style property will be addressed by the changes pushed to the properties panell: https://github.com/shesha-io/shesha-framework/issues/2264
