### ISSUE TITLE
`Properties`, `CRUD APIs`, and `Views` tabs do not display associated information in Entity Configuration

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2005]
When properties, Crud APIs and Views tabs are clicked, the associated information do not display. A blank page below each tab is displayed

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/settings/entity-configs/configurator'
2. Click any entity
3. Navigate through on Properties, Crud APIs and Views
4. Actual Results: The blank below each tab is blank. The associated information is not displayed

**Expected behavior**
When each tab is clicked, the information associated to each tab should display

See the attached video: https://jam.dev/c/2f022a20-9eab-43fd-8c05-8907b02b4d74

![image](https://github.com/user-attachments/assets/7c2dd9a3-51a5-4d21-bfd1-6879829e461f)

![image](https://github.com/user-attachments/assets/4b1c76e5-8ad6-4788-a045-e2a903ae75be)

![image](https://github.com/user-attachments/assets/9965fb9d-04d9-42f6-8fd2-28ca7dbaf258)

**Comment by Tshepiso-R** [comment]
Hey @AlexStepantsov please be aware that this issue has reoccurred. See the screenshots below for reference.
https://function-adminportal-test.shesha.dev/settings/entity-configs/configurator

![image](https://github.com/user-attachments/assets/4aacb32b-9305-4593-ac4d-acc135e43109)

![image](https://github.com/user-attachments/assets/2cae0009-fa77-48e4-ab59-8555d8f34b07)

![image](https://github.com/user-attachments/assets/9c96e24b-64b7-45d4-8dac-7047371860b0)
