### ISSUE TITLE
`entityTtype` properties not displaying when customizing columns on `dataTable` or `entityPicker`

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#2026]
**Describe the bug**
When you attempt to customize columns either on the data table or entity picker, the properties of the selected Entity Type do not display.

**To Reproduce**
1. Go to '[https://function-adminportal-test.shesha.dev/](https://function-adminportal-test.shesha.dev/)'
2. Create a table-view form.
3. On the datatable configuration, click **Customize Columns**.
4. Add a column.
5. Click the **Property Name**.
6. Observe that properties do not display.

**Expected behavior**
The properties of the selected Entity Type should display when customizing columns in the data table or entity picker.

**Screenshots**
![image](https://github.com/user-attachments/assets/82550dde-3239-4158-92dc-53ad1bf0924b)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed and deployed, please check
