### ISSUE TITLE
By default, the dialog width is small, it should be changed to medium

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2029]
When a dialog form is configured, the dialog width is defaulted to small. Upon render, the dialogs are small and requires a manual update. This affected all configurations and new configurations. Initially, the default width was medium

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/shesha/forms'
2. Click on 'Create New' button
3. Check the size of the form
4. Actual Results: The dialog is small

**Expected behavior**
The default size should be updated to medium

![image](https://github.com/user-attachments/assets/bd4261b2-8e9d-4018-b8f3-14e8ba1c441a)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've set default to **medium**, but it differs from the previous behaviour. Empty value was treated as 900px and it's incorrect, we should user percent as default.
PS: the user is still able to set pixels manually if required
