### ISSUE TITLE
Recent changes in `Button` and `Button Group` impact layout and functionality

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#2038]
### Description:
Recent updates to the button and button group components have caused several issues affecting the layout and functionality of existing configurations.

### Issues and Fixes:

1. **Layout Changes:**
   - **Issue:** The button layout of existing button configurations has been altered.
   - **Image:**
     ![Layout Issue](https://github.com/user-attachments/assets/550eb22f-fdd1-4d25-95ab-be80dbe4f9c1)
   - **Expected Layout:** [Expected Layout](https://function-v0-37-adminportal-test.shesha.dev/)

2. **Configuration Reflection in Dialog:**
   - **Issue:** Changes to border type, border width, and background color are only visible after closing and reopening the dialog.
   - **Fix:** Implement real-time updates so changes are reflected immediately within the dialog.

3. **Clear Button for Background , Border and Color Properties on button group:**
   - **Issue:** Missing clear button for border color and color properties.
   - **Image:**
     ![Clear Button Missing](https://github.com/user-attachments/assets/2065cfb0-05b5-44eb-bb88-c5d9cee1c83a)
   - **Fix:** Add a clear button for these properties to allow users to reset their choices easily.

4. **Width Display in Dialog:**
   - **Issue:** The width displayed in the dialog does not reflect the default button widths and defaults to block.
   - **Image:**
     ![Width Display Issue](https://github.com/user-attachments/assets/37d79f1a-75dd-4a21-bb6b-5230cb0b149c)
   - **Fix:** Update the dialog to show the correct width. 
   
5. **Button Group Size Setting:**
   - **Issue:** The size setting is not functioning for button groups.
   - **Fix:** Ensure that the size setting applies correctly to all buttons within the group.

6. **Button Type in Groups:**
   - **Issue:** Button type configuration is not applying to buttons within a group.
   - **Configured Button:**
     ![Configured Button](https://github.com/user-attachments/assets/5fd4b365-bad2-4be5-a098-ef5a6b060b42)
   - **On Render:**
     ![On Render](https://github.com/user-attachments/assets/75386fd7-da07-4492-a090-6e5185d1fd7e)
   - **Fix:** Ensure that the button type configuration is properly applied to each button in the group context.

7. **Redundant Button Style Properties:**
   - **Issue:** Two properties for Button Style are redundant and perform the same function.
   - **Image:**
     ![Redundant Button Style](https://github.com/user-attachments/assets/faf242c3-e7dc-4c6b-9076-38e2798eff9d)
   - **Fix:** Consolidate these properties to eliminate redundancy and ensure they perform the intended function.

7. **Hidden Property has been omitted:**
   - **Issue:** Initially, there was a Hidden property for each button with button group property. Currenty the property has been omitted
   - **Fix:** Add the Hidden property for buttons within the button group component.

**Related issue:** #1877
**Related PR:** https://github.com/shesha-io/shesha-framework/pull/1919

**Comment by hlayisanimazuze** [comment]
Hi @czwe-01, See the outstanding issues from the above notes made

- Configuration Reflection in Dialog:

Issue: Changes to border type, border width, and background color etc are only visible after closing and reopening the dialog. The change should be applied to all the styling properties
Fix: Implement real-time updates so changes are reflected immediately within the dialog.

- Clear Button for Background , Border and Color Properties on button group:

Issue: Missing clear option for border color, background color and color properties.
Add a clear option for these properties to allow users to reset their choices easily.
