### ISSUE TITLE
Form settings changes

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2042]
- When you console arguments `onValuesUpdate`, the logs are logged. When the form updates, the variables are not logged: https://function-adminportal-test.shesha.dev/dynamic/testModule/mondayLife-details?id=14cd7476-7479-45e6-aecb-0f5da27f93ec
- Prepare submit Data/On Before Submit parentFormValues variable is not available when you check on arguments. This is mostly used when a dialog requires the parentID/data. example: ReferenceList uses the parentFormValues: https://function-adminportal-test.shesha.dev/dynamic/shesha/reference-list-details?id=e5e12fde-dba2-445b-9985-9df0c3388388
- OnAfterDataLoaded: Query and initialValues variables are not defined. There's a project that uses the query variable
- There was initialValues settings initially, is this not required anymore from the latest changes? 
![image](https://github.com/user-attachments/assets/ff84b31c-da0a-44a4-996f-c1ad0f3f3dfe)

OnAfterDataLoad
- I setGlobalState and when I console globalState or check it on arguments, the value does not get logged on globalState. Example: https://function-adminportal-test.shesha.dev/dynamic/testModule/mondayLife-details?id=807a475a-ae02-44c3-9cf4-11e7cf144556
    - Navigate to the designer form
    - Click on form settings and click onAfterDataLoad
    - Enable the setGlobalState script and save the changes
    - Render the above form and check if the globalState is logged

- I declared a value on pageContext, and on arguments it logs as undefined. I have to tap on contexts for me to access pageContext. The stand alone pageContext does not work anymore?
![image](https://github.com/user-attachments/assets/f6af2f25-1d69-4e5c-a831-0cabfe762dc4)

- I can't setGlobalState PrepareSubmit Data, onBeforeSubmit and onSubmitSuccess, unless if I am using it incorrectly.
- pageContext is not undefined also on PrepareSubmit Data, onBeforeSubmit and onSubmitSuccess, inlcuding tapping on contexts. Is it not required?

-There was exclude'_formFields' in the payload option before, is it not required anymore?
![image](https://github.com/user-attachments/assets/0d2a3912-d43a-4c20-b519-972039292582)

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, I noticed that the variables defined in each form setting are now consistent, with the same variables used throughout. When comparing the variables in the old changes (e.g., in OnBeforeDataLoad, we had ParentFormValues and InitialValues exposed as arguments), these variables are not present in the latest changes. Should we stick with the latest changes, or do we need to add these variables to align with the old implementation?

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've made all required changes, you can find details on internal wiki. I think we also need to update our public documentation
