### ISSUE TITLE
Old detail view configuration forms with onInitialise pageContext script fail to open when navigating to record details

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2049]
Initially there was a line added on the details view template:  pageContext.setFieldValue('modelType', form.formSettings.modelType)
};, which is currently breaking the details view when you navigate to the details because Cannot read properties of undefined (reading 'setFieldValue')

We had to manually comment out that line for the details view to work

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/payment-audit-table'
2. Click on 'magnifying glass' icon to drill down
3. Actual Results: Immediately when you land on the details, an error is thrown: `Cannot read properties of undefined (reading 'setFieldValue')`

**Expected behavior**
If the line is not used anymore, it should be auto-commented out without a user having to re-configure/update their configurations

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've added a DB migration to fix it. Fixed and deployed, you can check
