### ISSUE TITLE
Expose an action on Wizard actions to reset the wizard state

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2093]
Add functionality to reset the Wizard state: For instance, if a user is on the last step and needs to add another claim, the Wizard should reset back to the first step.

**Comment by Lukeybooi** [comment]
## Resolution to Reset Steps
![image](https://github.com/user-attachments/assets/4b6b9bb4-a113-4b98-b0c0-89c991332983)

**Comment by hlayisanimazuze** [comment]
Clearing of the form fields will be handled by this work item: #2156
