### ISSUE TITLE
When additional fields are specified for fetching, the endpoint does not retrieve those properties

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2108]
When additional fields to fetch are specified on the form settings, after the get endpoint renders, the additional fields are not added on the list of properties

**Steps to reproduce the behavior:**
1. Open your developer console
2. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/fridayView-details?id=b7f0594e-9a6b-478d-bf35-e71962070507&firstName=Ernest%20Test&lastName=Nyumbu%20Updated'
3. Click on 'get properties' endpoint
5. Check if fullName, address.latitude and gender is part of the list
6. Actual Results: The properties defined on the form settings are not listed

**Expected behavior**
The endpoint should get the additional properties defined

![image](https://github.com/user-attachments/assets/71620058-a9f5-4c3f-a99e-108b059814db)

![image](https://github.com/user-attachments/assets/b85d38bf-a987-4b7e-96bb-882d8abb28ec)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
