### ISSUE TITLE
Entity Picker: Nested display property not shown in read-only mode

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2157]
After resolving [issue #2067](https://github.com/shesha-io/shesha-framework/issues/2067), when viewing details with a displayName set as a nested property, the value does not display in read-only mode. However, the value becomes visible when the form is switched to edit mode

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/newtest-details?id=744cb98e-0f9c-402d-803c-764112c88924'
2. Check 'Bank' field
3. Actual Results: The value does not show
4. Click on 'edit' pencil
5. Actual Results: The value does display

**Expected behavior**
The display value should display the same as the autocomplete

See attached video: https://jam.dev/c/2d8c8152-6449-474d-b0b8-8e7a6e7cd2f7

**Comment by Tshepiso-R** [comment]
Hey @AlexStepantsov, please note that this issue is occurring
https://functional-adminportal-test.azurewebsites.net/dynamic/TestModule/detais-form?id=792e7691-0a37-4b65-947c-0076315d5878

**Comment by hlayisanimazuze** [comment]
Hi @Tshepiso-R , the release builds are not working, that is the reason we don't have the changes. Let's wait until it is fixed, to test the work items

**Comment by hlayisanimazuze** [comment]
To be included on release 0.40.0
