### ISSUE TITLE
Prevent people from using ‘Shesha’ as the organization name from the starter project creator page

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#2194]
### Overview
Some users are using Shesha as the organization name on creating a starter project. Created some issues as it illustrated in this [discord conversation](https://discord.com/channels/1145298830573699093/1145298830573699096/1288089308523270226)

### Acceptance Criteria
- Prevent users from using ‘Shesha’ in the organization name field for https://www.shesha.io/get-started-with-shesha

**Comment by hlayisanimazuze** [comment]
![image](https://github.com/user-attachments/assets/ef620e7a-8c9d-4c3f-b748-102fd1aa1c74)
