### ISSUE TITLE
Console error occurs when opening code editors in form settings

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2223]
When opening the query builders within the form settings, an error is thrown in the console. This issue occurs consistently, preventing smooth usage of the query builder feature in form settings. 

_Note: The only code editor that opens successfully is 'Prepare submit data'._

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=7c44d418-5d8f-4947-9948-41486b6f0798'
2. Click on 'Settings'
3. Open developer console
4. Click any code editor
5. See error: `constantsBuilder is not defined`

**Expected behavior**
The code editors  should open without any errors being logged in the console

![image](https://github.com/user-attachments/assets/20fa3e90-463f-4e1b-bf01-74cacc70def7)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
