### ISSUE TITLE
Text component not updating in form designer

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#2230]
When you try to apply properties such as "Strong?", "Italic?", "Ellipsis?" and some others, the Text component does not automatically reflect the change. 

In order to see the change you need to switch to preview mode then back to edit mode and then only will the text update. Its also worth noting that every time you do the process above you loose your place on the property panel and then you need to scroll down again a few times to get back to where you were.

**Comment by hlayisanimazuze** [comment]
Hi @AlexanderSlavchovUX, The card has been merged with https://github.com/shesha-io/shesha-framework/issues/2318. We will close this one
