### ISSUE TITLE
Viewing properties with a code editor triggers an error for certain components

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2235]
Whe you click the below properties on the components,` metadataBuilder.addAllStandard` is not a function error gets displayed on most of them, except HTML Render property has a different error

- **Wizard**: Step Custom Enabled, Style, Custom Visibility
- **Section Separator**: Container Style and Title Style
- **Entity Picker**: OnChange
- **HTML Render**: Render HTML Code editor: `mb.addObject is not a function`
- **Rate**: OnChange and Style

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=11fef4d5-17b0-44fd-a9d6-f3f4d41137ad'
2. Drag and drop the mentioned components above and check each property mentioned
5. Open console
6. Click on the code editor
7. See error: `metadataBuilder.addAllStandard is not a function` or `mb.addObject is not a function`

**Expected behavior**
The code editor should open without displaying the error

![image](https://github.com/user-attachments/assets/e415309c-4fbe-4f2a-9f43-7cf8ae86264c)

![image](https://github.com/user-attachments/assets/7a264d32-a7d3-43ff-8f80-d4711efaa70a)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
