### ISSUE TITLE
Default navigation URL redirects to login instead of the configured URL

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2240]
When a default URL is configured in the system, accessing the system URL incorrectly redirects the user to the login page instead of the configured default URL

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/'
2. Immediately the link navigates to login page, instead of the default url

Check the release branch: https://functional-v0-39-adminportal-test.azurewebsites.net/
Actual Results: It navigates to the correct default url

**Expected behavior**
If a default url is configured, upon accessing the system URL, it should navigates to the url

![image](https://github.com/user-attachments/assets/06d6bfd9-c86e-458b-86ce-7e2f080d2e14)

**Comment by hlayisanimazuze** [comment]
Related #https://github.com/shesha-io/shesha-framework/issues/1530

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
