### ISSUE TITLE
Default navigation form does not inherit the configured primary color

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2246]
When a default URL is configured to replace the login page according to #2240 , clicking the system domain URL still displays the default page with the blue color instead of applying the configured primary color fix https://github.com/shesha-io/shesha-framework/issues/1871

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/'
2. See the colors displaying when the navigation page displays
3. Actual Results: The page still uses the blue color, instead of the configured page: https://jam.dev/c/c5b9f6f9-f699-4f7f-a48b-a486fab31ec4

**Expected behavior**
The default landing page should inherit the configured primary color

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
