### ISSUE TITLE
Image URL failing on all forgot password forms

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2259]
The URL that was used on all the forgot password forms: "https://starter-adminportal-test.shesha.dev/images/app-logo.png" is failing and the URL itself is down

- Replace the old image ULR that was used on all the forgot password forms and another one. What about e.g. https://raw.githubusercontent.com/shesha-io/shesha-framework/refs/heads/main/shesha-starter/frontend/public/images/app-logo.png? 

![image](https://github.com/user-attachments/assets/7dcbb9b9-f861-4847-9eaa-5c46e048319e)

**Comment by hlayisanimazuze** [comment]
Hi @teboho, the PR has been merged, however it seems like you only updated the first form of forgor-password and the rest of the forms are not updated. Please check the entire forms related to forgot password and update accordingly

![image](https://github.com/user-attachments/assets/91deb36c-2b72-4062-880c-ff3c02a01ac9)

**Comment by teboho** [comment]
> Hi @teboho, the PR has been merged, however it seems like you only updated the first form of forgor-password and the rest of the forms are not updated. Please check the entire forms related to forgot password and update accordingly First Page ![image](https://private-user-images.githubusercontent.com/151041759/382273187-d44e7f47-0564-4e3b-8a61-97242976ec32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mjc0MzEsIm5iZiI6MTczMDcyNzEzMSwicGF0aCI6Ii8xNTEwNDE3NTkvMzgyMjczMTg3LWQ0NGU3ZjQ3LTA1NjQtNGUzYi04YTYxLTk3MjQyOTc2ZWMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMzMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ2NWU0MmMxOWM4MDA2MjIxYjE0MWIyZjdhYWI0NjU5MGY4NzcyNzE4YWJlMmJkMTQ1OTc1NzNlZjQ5ZmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JYdp9uhgW7H9BVF7nkIPW6rvbBIQqGnHMAOQ367wc_o)
> 
> The rest are like this ![image](https://private-user-images.githubusercontent.com/151041759/382273083-91deb36c-2b72-4062-880c-ff3c02a01ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mjc0MzEsIm5iZiI6MTczMDcyNzEzMSwicGF0aCI6Ii8xNTEwNDE3NTkvMzgyMjczMDgzLTkxZGViMzZjLTJiNzItNDA2Mi04ODBjLWZmM2MwMmEwMWFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMzMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTViMmYyYjI4OTZiODZlMjEwM2MyMmE0NDE0MTA2NWI0MmM5MDRkMGYzMTkxOGM1YjEwODdjMzllNWQ2MGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AmLqNGvrhoS7UVyoUMw1UJ1fP2sJ9pW2DUZny-E3oME)

List
forgot-password
select-reset-method
email-sent-success
email-link-verification
otp-verification-page
reset-password
reset-password-options-error
invalid-email-link

**Comment by hlayisanimazuze** [comment]
Part of release 40
