### ISSUE TITLE
Button Group Configuration Enhancement

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#2261]
Currently when you add a button group to a Shesha form and try to configure it, you can only select the item in the button group if you select the drop handle on the item. 

Clicking anywhere on the item within the button group does not reveal the properties panel and this could feel like a bug to a user as it did to me originally. 

The drop handles are hidden by default and not an expected behavior on Shesha, can we implement it so that you can select anywhere in the white space on an item in the button group to be able to select the item to reveal the properties? 

![Button Group](https://github.com/user-attachments/assets/5ad358fd-6fab-4e7c-9351-50efff309f81)

**Comment by hlayisanimazuze** [comment]
Hi @AlexanderSlavchovUX , Ian created another item related to this, listing all the components that should behave the same way as you were illustrating in this card. I’ve linked that card, and I will close this one
