### ISSUE TITLE
Header background color does not apply in the new panel styling

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2266]
After updating the design of the panel component, the configured header background color does not apply to the component's header when `hide top bar` property is false

**Steps to reproduce the behavior:**
1. Go to  'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=5ee2ce43-d6d9-464c-918d-bc7df840e4b6'
2. Click on 'Panel Component'
3. Scroll down to 'header background color' property
4. Configured a color and preview the form
5. Actual Results: The header background color does not apply to the panel's header, even though a color is configured in the settings. The header remains the default color or shows no background color change.

**Expected behavior**
The configured header background color should be correctly applied to the panel's header when the panel is rendered, reflecting the specified color in the settings.

Current Changes (if you look at the top right corner of the panel, you would see a lil bit of red)
![image](https://github.com/user-attachments/assets/b7df88ae-c181-4674-b32a-a9638e8e2527)

Old Changes with background header color
![image](https://github.com/user-attachments/assets/461a0014-639c-4d17-ab6f-25a8244d91b8)

**Comment by hlayisanimazuze** [comment]
Related #699

**Comment by teboho** [comment]
will be tested first
