### ISSUE TITLE
Kanban component update

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2287]
1. When a change has been made on the referenceList, the component requires reconfiguring to pull the latest changes made on the component. This affect Chevron and Kanban
2. If nothing is set from the configuration, the Setting and 3dots should not show
3. onDropConfiguration action they get triggered twice instead of getting triggered the moment the record is dropped. Example: If a show message is configured, it is triggered twice even before dropping the record
4. Touching the record triggers the configuration action

**Comment by hlayisanimazuze** [comment]
Related item #2262

**Comment by Tshepo1103-lab** [comment]
@hlayisanimazuze I did change the tooltip message
