### ISSUE TITLE
Entity Reference compoent link is disabled if Edit Mode is 'Readonly'

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#2308]
### Steps to Reproduce
1. Add an entity reference component and configure appropriately
2. set 'Edit mode' config property to 'Read only'
3. Render the form
4. Error: Link To the referenced entity is disabled
![image](https://github.com/user-attachments/assets/c194b4c7-97cf-419e-8552-bafc0507be78)

### Expected behavior
1. Link should not be disabled even when not editable
2. Edit mode property in fact does not make sense for this component and should be removed since it is not an editable component
3. This should apply whether using Navigate Link or Quickview

**Comment by AlexStepantsov** [comment]
There was an architectural issue with the hierarchical read only mode. Fixed
