### ISSUE TITLE
Unable to scroll to view additional properties in Wizard, Tab, and Entity Configuration

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2313]
When configuring Wizard and Tab steps, clicking on a step displays a limited number of components in the properties panel. However, the remaining components are not visible due to the screen size, and a scrollbar is not available.

For Entity Configuration, when the properties list is lengthy, only a portion of the properties is displayed. The container at the bottom prevents scrolling to view the entire list

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=7bab0099-6a88-4974-ac5e-b470bb090a52'
2. Click on 'Wizard/Tab'
3. Scroll down to 'Configure steps/tab panes' depending on the component used
4. Add a new step and check the list of properties displayed on the properties panel
5. Actual Results: Not all properties are displayed and there is no scroller. See attached: https://jam.dev/c/c1575d90-bb2b-4bad-acd6-fbfa96b92a2a

**Entity Configuration**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/settings/entity-configs/configurator'
2. Search for 'Member' and click it
3. Click on 'Properties' tab afterwards
4. Scroll down from the list till the bottom
5. Click one property and check the properties panel
6. Scroll down to see all the properties available for the selected property
7. Actual Results: Not all properties are displayed due to the container available at the bottom. See attached: https://jam.dev/c/ba893929-1d45-4470-8ce0-6196432af62e

**Expected behavior**

- Wizard and Tab: When clicking on a step, the properties panel should display all relevant components, with a scrollbar available if the content exceeds the visible area, allowing users to scroll and access all components.
- The properties list should display all properties correctly. If the list is lengthy, a scrollbar should be present, enabling users to scroll down and view all properties without obstruction from any bottom container.

**Comment by AlexStepantsov** [comment]
Hi @James-Baloyi 

Probably new FormInfo component breaks styles for displaying properties panel in ListEditorWithPropertiesPanel
 
Please check and fix

[Unable to scroll to view additional properties in Wizard, Tab, and Entity Configuration #2313](https://github.com/shesha-io/shesha-framework/issues/2313)

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi , I am not sure if you saw the Entity Configuration repro steps as well. The commit only fixed Tab and Wizard, the entity configuration properties panel is still behaving the same way I've written above. https://functional-adminportal-test.azurewebsites.net/settings/entity-configs/configurator

**Comment by James-Baloyi** [comment]
@AlexStepantsov Hlayi's comment is what I was trying to fix with the suggestion I sent in Teams, but I returned the children without wrapping them in the edit mode UI instead when there's no formProps.id, which means there are no props to show.

**Comment by Tshepiso-R** [comment]
PR

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi, I see the PR has been merged and the entity configuration issue is fixed. I'm closing the item
