### ISSUE TITLE
Text Component fails to update in real-time and ellipsis/copy icon alignment issues

### ISSUE THREAD

**Issue by miracleMa** [shesha-io/shesha-framework#2318]
**Describe the bug**  

- The text component no longer auto-updates in real-time when certain properties are selected in designer mode. You have to preview  or  render first to verify if changes have been applied.  
- Additionally, when using the ellipsis property, if the content exceeds the container, the ellipsis should appear. Currently, the ellipsis is not visible, and the text is simply cut off. When the copy property is enabled, the copy icon does not align with the text.  
- Its also worth noting that every time you do the process above you loose your place on the property panel and then you need to scroll down again a few times to get back to where you were.

**Steps to reproduce the first issue:**  
1. Go to 'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=1d45e4ef-2097-43a1-a6d7-910abf161e93'  
2. Drag and drop the Text component.  
3. Navigate to 'Content' on the properties panel and type in any text.  
4. Observe the error: Notice that if you check the following properties, you won't see real-time updates unless you first preview or render:  
   - Code Style  
   - Italic  
   - Keyboard style  
   - Delete  
   - Strong  
   - Underline  

**Expected behavior**  
The text component should update in real-time when selecting properties, even in designer mode

**Second Issue**

**To Reproduce**  
1. Drag and drop the Text component.  
2. Enter content long enough to trigger the ellipsis.  
3. Set the Ellipsis property to true.  
4. Save and render.  
5. Observe the error: The ellipsis is not visible, and the text gets cut off.  
6. Also set the copy property to true
7. Save and render
8. observe the error: The copy icon does not align with the text
![image](https://github.com/user-attachments/assets/0928190d-c535-4e4f-8ff0-7d93e13052cc)

**Expected behavior** 
The copy icon should align with the text.

**Comment by Tshepiso-R** [comment]
Related Item: #2230

**Comment by Tshepiso-R** [comment]
@AlexanderSlavchovUX The card has been merged with #2318.

**Comment by hlayisanimazuze** [comment]
Part of release 40
