### ISSUE TITLE
Make dataTableContext refreshing more intuitive

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2355]
**Description**: "When a dataTableContext is manually refreshed via a script, the applied filters on the dataTableContext are not retained.

  - **Required Solution 1:** Allow filters to be passed when a dataTableContext is manually refreshed via a script.

**Description**: When a wizard component is rendered within a dialog, the wizard’s actions are used. As a result, closing the modal containing the wizard does not allow the refresh of the dataTableContext that exists outside the modal
   - **Required Solution2:** Enable dataTableContext refresh from outside the modal upon closing a modal containing a wizard component.

**Comment by AlexStepantsov** [comment]
Added "Disable refresh data" expression setting. Need to return 'true' if datatable Context is not ready to refresh data (filter data is not ready, etc...). Eliminates table refresh and sending unnecessary "empty" requests to the backend if there is not enough data to form the request (there is no data for correct filtering). It is necessary to replace the "Hidden" hack for datatableContext

**Comment by AlexStepantsov** [comment]
I also checked refreshig tables via script and this feature is working fine (`globalState.dataTableContext.refreshTable()`)
