### ISSUE TITLE
ReferenceList item with '0' value not displayed in dataTable with default display component or referenceListStatus or statusTag

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2379]
When a referenceList item has a value of '0' and is rendered in a table using the default display component or referenceListStatus or statusTag, or when rendered on the details view with referenceListStatus, the value '0' does not display

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/shesha/forms-designer?id=a34527dd-dc3a-4c3b-8055-a94dd20c98fc'
2. Click on 'dataTable' component and click on configure Columns from the properties panel
3.Click on 'MembershipStatus' column
4. Scroll down from the properties panel and click on display component and select default option
5. Save the changes and preview the form
6. Search for 'Support For 0' and check membershipStatus value
7. Actual Results: The value does not show
8. Repeat step 2-3, then select 'ReferenceListStatus component as a display
9. Save your changes, then preview
10. Actual Results: The value does not show

NB: If you update the display component to dropdown, the value does display

Details View
- Drill down to the details of Support For 0 and check the second membership status property
- Actual Results: The value does not show

**Expected behavior**
Default display and referenceListStatus should be able to render a '0' value

**Comment by hlayisanimazuze** [comment]
Related: https://github.com/shesha-io/shesha-framework/issues/2289

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, URL: https://functional-adminportal-test.azurewebsites.net/dynamic/TestModule/bugfixes-table

- DataTable: With the default display setting on the dataTable is still not pulling the '0' value
- StatusTag: If the component is using 'manual' value source, it does not pull the '0' value. Drill down to the details view

**Comment by Tshepiso-R** [comment]
Hi @AlexStepantsov, I have noted that the first comment from @hlayisanimazuze is resolved. Please advice if you were able to take a look at this one. the issue still persist.
https://functional-adminportal-test.azurewebsites.net/dynamic/TestModule/test-min-max-table
**StatusTag: If the component is using 'manual' value source, it does not pull the '0' value. Drill down to the details view**
![image](https://github.com/user-attachments/assets/d3a6ee54-5779-435b-9441-58d9b7f9918f)

**Comment by hlayisanimazuze** [comment]
Hi @Tshepiso-R, let's create a separate card and put it in the backlog
