### ISSUE TITLE
After logging out and back in without refresh, user is redirected to previous page instead of configured home URL/default landing page

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2383]
When you log out from a specific page and then log back in without refreshing, the application redirects you to the previous page instead of the configured home URL or default landing page of the system. This behavior bypasses the home URL configurations, as it takes you back to the page you were on before logging out

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/'
2. Login
3. Navigate to any page on the side menu
4. Afterwards, click on logout
5. Re-login again without refreshing the page
6. Actual Results: The system navigates to the previous page you were at, instead of the default landing page. This also affect the behaviour of the home url configurations from enterprise

**Expected behavior**
Upon re-logging in, the system should redirect the user to the configured default landing page or home URL, rather than returning to the previous page they were on before logging out

**Screenshots**

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, If we implement this fix, won't it affect the behavior where, if someone sends a specific URL, the system navigates to that URL upon logging in?

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It was fixed as part of the #2512
