### ISSUE TITLE
Cancelling edit reverts to old changes instead of the latest saved data

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2400]
After updating and saving details in the view, if the page is not refreshed and the user clicks "Edit" and then "Cancel" without making further changes, the system incorrectly pulls in the previous data (the data before the update), rather than displaying the latest saved data.

**Steps to reproduce the behavior:**
1. Navigate to: https://functional-adminportal-test.azurewebsites.net/dynamic/testmodule/cancel-edit-details?id=1fa6ca36-ceaf-4ae7-aae2-6762e79ad124
2. Update the details in the view and save the changes.
3. Without refreshing the page, click the "Edit" button.
4. Click "Cancel" without making any additional changes.
5. Observe that the system pulls in the previous data (before the update), not the latest saved data.
6. Actual Result: The system displays the previous data (prior to the update), causing confusion and potentially leading to data inconsistencies.

**Expected behavior**
After clicking "Cancel" from the edit mode, the system should show the most recently saved data, reflecting the update made earlier.

NB: If you handle success after cancelling to refresh the form, it pulls the correct info

**Comment by hlayisanimazuze** [comment]
Related: https://github.com/shesha-io/shesha-framework/issues/2393

**Comment by Tshepo1103-lab** [comment]
Hi @hlayisanimazuze

Ivan pushed a fix for this issue:
https://github.com/shesha-io/shesha-framework/pull/2443
