### ISSUE TITLE
Address event variable is missing (suburb and town) properties

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#2447]
#### **Describe the Bug**  
When the address component is configured with corresponding fields (Latitude, Longitude, Suburb, and Town), selecting an address should auto-populate these fields with relevant data. However, the fields do not populate as expected. Upon inspecting the console, the `event.town` and `event.suburb` properties are missing from the object. While some addresses still return these properties, others that previously worked no longer do.

#### **To Reproduce**  
Steps to reproduce the issue:  
1. Navigate to: [[Address Component Table](https://functional-adminportal-test.azurewebsites.net/dynamic/Shesha/address-component-table)](https://functional-adminportal-test.azurewebsites.net/dynamic/Shesha/address-component-table).  
2. Click on **'Add Me'** to add a new entry.  
3. Open the browser's developer console.  
4. In the "Address1" input field, search for and select an address.  
5. Observe the following issues:
   - The fields (Latitude, Longitude, Suburb, and Town) remain unpopulated.  
   - The console output does not include the `town` and `suburb` properties for certain addresses.

#### **Expected Behavior**  
Selecting an address should auto-populate the following fields with corresponding values:  
- **Latitude**  
- **Longitude**  
- **Suburb**  
- **Town**  

Additionally, the console should log all properties, including `event.town` and `event.suburb`.

#### **Screenshots**  
![Bug Screenshot](https://github.com/user-attachments/assets/a1cbe6c4-c974-4ebc-9a67-316d935385f9)

**Comment by Lukeybooi** [comment]
Hi @Tshepiso-R this is a configuration issue. Please note that suburb and town data will not always be available. I've set a default for town which is city. Try something like `265 Pretorius Street.
