### ISSUE TITLE
Menu item addition and drag-and-drop issue

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#2493]
## Describe the Bug
When attempting to add a new menu item using the hover functionality, the new menu item does not display immediately. It only appears after clicking the "Add New Item" button, resulting in two menu items being added (one from the hover attempt and another from the button click). Additionally, when dragging and dropping a menu item to a group, the item is misplaced into a random group instead of the intended one.

## To Reproduce
1. Go to [Functional Admin Portal Test](https://functional-adminportal-test.azurewebsites.net/).
2. Enable "Edit Mode."
3. Click the "Edit Sidebar" button.
4. Attempt to add a new menu item to a group using the hover functionality.
   - Observe that the newly added item does not display.
5. Click the "Add New Item" button.
   - Observe that two new items are added: one from the hover attempt and another from the button click.
6. Drag and drop an item to a specific group.
   - Observe that the item gets misplaced and ends up in a random group.

## Expected Behavior
1. Adding a menu item using the hover functionality should immediately display the item in the correct group.
2. Clicking the "Add New Item" button should add only one item and not duplicate any previous action.
3. Dragging and dropping a menu item should result in the item being placed accurately in the selected group.

## Actual Behavior
1. Items added using the hover functionality are not displayed until the "Add New Item" button is clicked.
2. Clicking the "Add New Item" button results in duplication, adding two items instead of one.
3. Dragging and dropping a menu item places it in a random group instead of the intended one.

## Screenshots

https://www.awesomescreenshot.com/video/34250410?key=68351edde1b175b70bf0ccfd25718cae

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
