### ISSUE TITLE
Inconsistent Font Style on Permissioned Objects Page

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2511]
**Steps to reproduce the behavior:**

1. Navigate to [Permissioned Objects Page](https://functional-adminportal-test.azurewebsites.net/dynamic/Shesha/permissioned-objects).
2. Scroll down and locate the tokenAuth object (as an example).
3. Expand the appService section.
4. Observe the font style of the appService and its endpoints.

**Actual Results:**
The endpoints and appService are displayed in bold font

**Expected behavior**
The font style of both appService and its endpoints should be consistent and not bolded

![image](https://github.com/user-attachments/assets/bce6c54b-bf60-4651-9037-f1dfb648d44d)
![image](https://github.com/user-attachments/assets/3ff46038-6afd-4e69-92cf-0e3ed62c7499)
![image](https://github.com/user-attachments/assets/6ef5b7cc-7273-48d9-80ff-747641c41081)
![image](https://github.com/user-attachments/assets/d38d6994-2a30-436f-9c15-323edb5973f6)

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov , I initially added this as part of this https://github.com/shesha-io/shesha-framework/issues/2506, but I see you might have missed the comment

**Comment by AlexStepantsov** [comment]
added tooltip

![image](https://github.com/user-attachments/assets/d956edb7-d450-4150-8e93-ed668be62fc2)
