### ISSUE TITLE
Home URL routing navigates to the default landing page instead of the specified dynamic URL

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2512]
If the homeURL is configured to use a dynamic URL instead of the default url, upon logging in, the getCurrentLogin gets the default url instead of the dynamic url. 

Example from enterprise
1. Navigate to: https://pd-enterprisepr-adminportal-test.azurewebsites.net/
2. Username: homes and password (default password used internally) and click signin
3. Actual Results: Upon signing in, the user will be directed to the default landing page, instead of the configured url. Configured homeurl: /dynamic/Shesha.Enterprise/organisation-units

Expected Results: If the user logging in has a dynamic URL configured, the application should navigate to that URL upon login. If no configured URL is available, the default URL should be used

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've found and fixed two problems:
1. Handling of the current url on the user login, related issue: #2383
2. Handling of http headers. **GetCurrentLoginInfo** request must contain **sha-frontend-application** header (see attached image).

![image](https://github.com/user-attachments/assets/17c72008-e2a1-4b27-ac59-8684b2368756)
