### ISSUE TITLE
CSS and layout improvements of the forms designer

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#502]
**CSS and layout improvements of the forms designer**
1. Scrolling of the left and right panels should be independent
2. Make the right and left panels resizeable and the default size should be smaller
3. Reduce padding size on component list
4. Add bottom padding on the left panel
5. On left panel make 'Widgets' and 'Data' sections as tabs

6. Add buttons to access form history and form details, and duplicate buttons from the details view. 
Forms designer page should allow to:
- navigate to the form details view
- perform all the same operations as it's done on the details view (`Get Json`, `Import Json` etc.)
- open form history modal with ability to view each version in the designer

**Comment by nthangeniphumudzo** [comment]
@hlayisanimazuze I believe poin 6 was ruled out in the meantime

**Comment by hlayisanimazuze** [comment]
Related item #1718

**Comment by hlayisanimazuze** [comment]
Requirement 6 has been parked until further notice

```
Add buttons to access form history and form details, and duplicate buttons from the details view.
Forms designer page should allow to:

navigate to the form details view
perform all the same operations as it's done on the details view (Get Json, Import Json etc.)
open form history modal with ability to view each version in the designer
```
