### ISSUE TITLE
Remove all obsolete components from the @shesha/reactjs

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#509]
@shesa/reactjs contains a lot of components which were added in the very first version of the library when forms designer was under construction. We need to do a clean-up and remove all legacy code

**Comment by AlexStepantsov** [comment]
All old components have been cleaned up and unnecessary code removed. Migrations have been left that change old components to new ones. It is also possible to see the settings of some legacy components if there is a need for manual migration.

All remaining code of legacy components has been moved to a special folder for isolation from other components.

This saves us from having to completely remove the code and additionally notify users about component changes and the need to validate forms.

This is a safer and "cheaper" solution

**Comment by hlayisanimazuze** [comment]
I've seen this on DEP, they upgraded to the internal builds that had this change and on the old 'list' component, it displayed an message that they should use the latest component
