### ISSUE TITLE
Remove ChildTable component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#510]
Remove ChildTable component, it should be replaced with a combination of other components.
1. Filters + CurrentFilter properties should be replaced with a single property Filter and it should be moved to the DataTableContext component
2. Add a migration to the component the will create a set of components (panel + buttonGroup + datatable)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've implemented it, please check. 
ChildTables on the existing forms were automatically converted to a combination of Panel + QuickSearch + Pager + ButtonGroup. _Filters_ and _Selected Filter_ properties were moved to a new setting - _Permanent Filter_ on the DataTableContext level. Permanent filter is always applied irrespectively of other filters.
