### ISSUE TITLE
Review handling of the environment variables in the react applications

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#513]
Review handling of the environment variables in the react applications, currently our application includes some sensitive data into the html pages. We need to pass environment variables by a safe way (check https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables). Note: it may require update of the pipelines. It also may be a one of reasons of hydration errors generated by NextJs

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It was implemented earlier. Currently front-end application uses environment variable `BACKEND_URL`
