### ISSUE TITLE
Upgrade react applications to the latest NextJs version

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#519]
1. Upgrade react applications to the latest NextJs version
2. Remove NextJs dependency from the @shesha/reactjs. Next router should be isolated using a new interface
3. Fix hydration problem, see below
_`Error: Hydration failed because the initial UI does not match what was rendered on the server. See more info here:`_ https://nextjs.org/docs/messages/react-hydration-error

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Application was updated to uses latest NextJS (currently it's 14.0.4), note that @shesha/reactjs still uses nextjs as a dependency for a simplification of debugging process.
