### ISSUE TITLE
Null values appear in DataTable columns and subform when utilizing a number field to display data

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#523]
When utilizing the number field to display data, the column displays "null" in cells that do not contain any data including subform. If the column uses the default display component, it does not display null and on a subform

**Steps to reproduce the behavior:**

1. Click on this link: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=bbdf0d01-f33c-44c1-803e-b8db2aea1ab3
2. Go to the datatable configurations
3. Click Configure Columns and add a new column
4. Bind the column to a property
5. From the Display Component dropdown, select "Number field"
6. Save and Render the form

**Expected behavior**
When utilizing the number field to display data, the column must not display "null" in cells containing no data..

![Null](https://github.com/shesha-io/shesha-framework/assets/151041759/092d3604-7c34-4401-a306-30d63e42687d)

![Nulls](https://github.com/shesha-io/shesha-framework/assets/151041759/90479393-9158-4d1b-a48e-e9a69a5e6d16)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
