### ISSUE TITLE
The custom buttons fail to adhere to form validations

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#535]
If you choose to utilise custom buttons rather than the default buttons, and your form includes required fields validation, attempting to submit the form without entering the necessary values results in a successful submission without any blocking mechanism

**Steps to reproduce the behavior:**

1. From this URL:  https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/Books-Table, render the form and click 'Add button' (the button is not disabled, while the property is set to true)
2. On 'Add New Book' form, you will notice that 'Name and Price' is mandatory from the form
3. Click on 'Save Book' button. NB: The button is custom

**Expected behavior**
The behavior should be the same as the default buttons(see attached screenshot), whereby it checks the mandatory fields and if they are empty, it displays an error message of 'this field is required' and the button should be disabled when the property is set to true

![Fields](https://github.com/shesha-io/shesha-framework/assets/151041759/035d45d5-d4db-4b1c-9488-a847b543761a)

**Comment by Tshepiso-R** [comment]
Related to:

- #676
