### ISSUE TITLE
Second autocomplete fails to clear selection when updating first autocomplete/dropdown

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#548]
Scenario 1: I have two autocompletes, the second is suppose to filter the data based on what have been selected on the first autocomplete. [https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=011a5a81-3ae4-4de5-ae52-d44ed150ed9f](https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=70be3592-99f6-49a1-8b7a-e3162896cf90)

Scenario 2: If you have dropdown and a autocomplete. The autocomplete filters the data based on what you have selected on the dropdown. https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=ab82e99d-66e4-446c-a88f-2b0a11154cf3

**Steps to reproduce the behavior:**

1. Select address, immediately the members will be filtered
2. Select a member on the second autocomplete. NB: Keep note of the selected value
3. Clear the value selected on member autocomplete
4. Select a new value on the first autocomplete
5. Click on the second autocomplete and check the value you selected from step 2
Actual Results: The selected value does not get cleared

**Expected behavior**
The selected value from the previous should be removed

**Comment by hlayisanimazuze** [comment]
Comment from DevOps

Hi @IvanIlyichev, can the same changes be applied when you search before selecting?

1. From the above links, select a value on the first autocomplete
2. Second Autocomplete: Instead of selecting from the options provided, search for a value then select it
3. Clear the value
4. Select a new value from Autocomplete 1
5. Click on 'Autocomplete 2 and you will see the values displaying are related to what you've searched

See attached videos: https://boxfusionint-my.sharepoint.com/:v:/g/personal/hlayisani_mazuze_boxfusion_io/EbCrxzkkMxlDk_TIc0-ypT4BRUuEdFMmqczaE_84Fra0NA?e=g63h3k

https://boxfusionint-my.sharepoint.com/:v:/g/personal/hlayisani_mazuze_boxfusion_io/EahPV-s45pdAv7YuhDMGjUIBivGg0cpT6g7Qyz2j75wJeQ?e=YQGHS2

NB: It caches the searched values, even on autocomplete 1

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I can't reproduce it on test now, looks like it was fixed earlier, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , I also can't reproduce it. I will close the item. We'll re-open if it re-occurs
