### ISSUE TITLE
Misalignment of data when displaying table data using 'default and 'Input field'

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#553]
The values displayed using the default display components are shifted slightly upwards, while the values displayed with text fields are vertically centered, resulting in misalignment.

**Steps to reproduce the behavior:**
1. Render this link: https://function-adminportal-test.shesha.dev/dynamic/Shesha/thirty-october
2. On the form designer, go to the `dataTable` configurations and add two columns
3. Bind the first column to a property and leave the display component as default
4. Bind the second column to a property and select Text Field as the the display property
5. Save and render the form

**Expected behavior**
Despite the display options used, the alignment of the values should be consistent.

![Alignment](https://github.com/shesha-io/shesha-framework/assets/151041759/89cd50d4-d474-4bf9-b9ac-867aef92ab66)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check

**Comment by Tshepiso-R** [comment]
Hi @IvanIlyichev, all the display components are aligned correctly, except for entity reference, which seems slightly shifted down. Please take a look at the attached screenshot below.
https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=5851d7ae-9f90-4349-9334-494861d223b7

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/0fa1cc1d-7880-4b6d-b51d-a83b25f33d18)

**Comment by IvanIlyichev** [comment]
Hi @Tshepiso-R. I've fixed it, please check
