### ISSUE TITLE
The DataList (and DataList) should be able to bind to and update a list of objects maintained on the front-end 

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#557]
1. It should be possible to bind the datalist to a list of objects maintained on the front-end
a. An example of this could be a JsonProperty that exposes a list of JsonObjects
a. Edits/Additions/Deletes should update the state but not call back-end CRUD APIs to persist changes
2. Saving of saves will either be managed by the parent entity (e.g. in case where DataList is bound to a list of JsonEntities, or by calling custom APIs

**Comment by hlayisanimazuze** [comment]
### Related Item

- #755
