### ISSUE TITLE
Date Field Display Component: If 'show time' is false, the table view still display time on date time property

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#588]
The Date Field Display Component is displaying time on the table view even when the 'show time' option is set to false.

**Steps to reproduce the behavior:**

1. Click on Customize columns
2. Click on Membership Start Date
3. Click on the Configure button on Display Component 
4. Provide the date format and the time format should be empty
5. Ensure the show time checkbox is false
6. Navigate back to the table view and check the results displaying

**Actual Results**
The time is also showing while the formatting does not include the time

**Expected behavior**

**Additional context**
 If the format is applied on Entity Configurations and the display component is set to Default, the format applies according to how it is specified on the configurations

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
