### ISSUE TITLE
Set Label Span and Column Span to 24

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#591]
The Column Span and Label Span by default should be 24 in total. Currently on the framework we have it set to 18 total. 
What is happening is that because of this we get an abnormal padding on the right on Modals and other components.

**Steps to reproduce the behavior:**

Form link: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=337fa5cd-c803-4bcc-9551-477c4c29b85c
1. Create a new form
2. From the form designer, click on "Settings"
3. Render the form
4. The default span is still the old one i.e. Label Span is 5 and Component span is 13. If you render the form, the components span are still defaulted to the one specified on the form settings

_See the screenshot below:_

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/4a30c564-adb8-424a-ad83-2e39cc7ed06c)

**Expected behavior**
We need to define what is a set value between label and component span to always equal 24 by default.
Label Span 6 and Column Span 18

**Additional Links**
https://heurio.app/project/WWxTaWFrdEd1L081a0JpeTFNTWZYZz09/all/233026/?view=severity&status=all&device=all
https://pd-inventory-adminportal-test.shesha.dev/shesha/forms-designer/?id=618801bc-87d3-4187-8576-cf8af7b68cf8

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, the card is saying the label span should be 6 and component should be 18. Please update according. If we use what you implemented, it leaves excessive space see attached

This is label 8 and 16 component
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/6959879b-6d25-4be2-8529-bfb48c448f6a)

This is label 6 and 18 component
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/10bdd17a-1dbe-427c-b56f-00bf2a4ac3a9)

**Comment by hlayisanimazuze** [comment]
@Lukeybooi, the changes for this card has been reverted back to the original span. Please check it

**Comment by OmolemoBlessingLethuloe** [comment]
To test: Create new forms from this site: [Starter Site](https://starter-adminportal-test.shesha.dev)
