### ISSUE TITLE
Add 'Style' properties to Layout components

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#592]
#### Story:
As a configurator, I want to have more flexibility in laying out components to easily apply basic paddings and margins without resorting to creating styles in the code editor. This will allow for a more refined control over the aesthetics of how the layout is presented.

#### Acceptance Criteria:
1. As a user configuring the layout, I should be able to apply basic padding to a layout component.
2. As a user configuring the layout, I should be able to apply basic margins to a layout component.
3. The styling properties for padding and margin should be easily accessible in the configuration interface.
4. The application of padding and margin should have an immediate visual impact on the layout.

#### Additional Information:
- Currently, configurators use columns or other items to create spacing between components (e.g., Container - Columns - Container).
- The proposed solution is to introduce basic styling properties for Padding and Margin for all layout components.
- The purpose is to provide a quick and efficient way to configure the visual layout without the need to insert elements between components for paddings or margins.

#### Definition of Done:
- The padding and margin properties are implemented for all layout components.
- The styling properties are accessible and configurable in the layout configuration interface.
- Changes in padding and margin have a noticeable effect on the visual presentation of the layout.

**Comment by hlayisanimazuze** [comment]
Awaiting for Alex Slavchov to confirm with Ian the current implementation

**Comment by AlexanderSlavchovUX** [comment]
Update Test

**Comment by hlayisanimazuze** [comment]
A new item #857 has been created to enhance the implementation covered in this item
