### ISSUE TITLE
Create a new "Quick Edit" form builder that opens in a large dialogue box rather than a new tab

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#593]
**Story**
This task is to create a new "Quick Edit" form builder. Traditionally we open the form builder in a new tab and configurators end up having multiple tabs open with different screens. This breaks the user flow and distracts the user from being able to do quick edits on the fly. 

**Acceptable Criteria**
The new implementation will allow us to click the form builder button to launch the full form builder in a dialogue box rather than a new tab. When the user is done they can save and close and return back to where they were. 

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/4c1beb77-6198-45f2-b6fe-3d70bfc6099e)

**Figma Designs in Dev mode with CSS can be found here:**
[https://www.figma.com/file/VZUSwY3d2LNZGi7nMcX0Fm/Shesha3-Design-Review?type=design&node-id=0%3A1&mode=dev](https://www.figma.com/file/VZUSwY3d2LNZGi7nMcX0Fm/Shesha3-Design-Review?type=design&node-id=0:1&mode=dev)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's implemented, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , may you please increase the size of the dialog width and height to be bigger. Refer to the attached example below

![LargerModal](https://github.com/shesha-io/shesha-framework/assets/151041759/7ed97a9c-ceac-41d7-867e-f4e45626fb1c)

**Comment by hlayisanimazuze** [comment]
A new item has been created to cover the comment request https://github.com/shesha-io/shesha-framework/issues/878
