### ISSUE TITLE
Update existing edit mode and implement new edit mode with icons

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#594]
**Story**
This task is to update the existing edit mode we use on Shesha3 to a new and more streamlined look and feel. This will allow better color coordination between which items are Live Mode and Edit Mode.

**Acceptable Criteria**
Once the edit mode toggle is selected a toast pops in to tell us that we are now in Edit Mode, the toast then disappears to a neutral state:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/7853d2c9-f49d-4aad-95ea-303b45c64ace)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/02e83fbd-f487-435e-a266-eec0e2a31520)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/c6f346de-c75a-4027-8995-7140a450c578)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/dbefd9f0-bb2b-4e5a-9719-eb38f135808e)

**Figma Designs in Dev mode with CSS can be found here:**
[https://www.figma.com/file/VZUSwY3d2LNZGi7nMcX0Fm/Shesha3-Design-Review?type=design&node-id=0%3A1&mode=dev](https://www.figma.com/file/VZUSwY3d2LNZGi7nMcX0Fm/Shesha3-Design-Review?type=design&node-id=0:1&mode=dev)

**Comment by hlayisanimazuze** [comment]
The functionality has been implemented. A related item: #1110 has been created to address cosmetic clean up
