### ISSUE TITLE
Only show dotted lines on hover

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#595]
**Story**
- Can we please remove the dotted lines indicated by the red arrow below so they are not always visible? 
- When you hover over a component or widget the blue dotted line outline should be shown as illustrated by the blue arrow

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/701ee0d1-074c-401a-937c-f2056323ba8f)
 
**Acceptable Criteria**

The goal is to reduce clutter on the form builder screen so that it is easier to see what is there on very busy screens.

**Comment by hlayisanimazuze** [comment]
@nthangeniphumudzo , please add the tag **ready for testing** once your PR has been approve. The changes are not showing on the function site as yet
