### ISSUE TITLE
Remove handles on form builder components

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#597]
**Story**
The handles on the form builder components need to be removed to allow more space to be created as too many of them can make the form builder very busy. 

Clicking anywhere within the widgets boundaries should select the widget in the same way that clicking the handle does. You should also still be able to drag and move around widgets by selecting anywhere inside their boundary box. 

**Please see related work items which also affects this behaviour.**

1. #595 
2. #581

**Comment by hlayisanimazuze** [comment]
I'm experiencing an issue when clicking the buttonGroup, if item #595  gets resolved it will make it easier to get the buttonGroup. I'm closing this item with the exception of the buttonGroup. If the issue still persists after the item has been resolved, I will reopen this item
