### ISSUE TITLE
Slightly increase drop target sizing on form builder

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#598]
#### Story:
As a configurator, I want an enhanced drag-and-drop experience when adding components to busy screens or moving them within a form. The current drop targets are challenging, leading to difficulties in accurately placing components, especially in crowded layouts.

#### Acceptance Criteria:

- As a user dragging a component, I should experience improved accuracy in dropping it onto busy screens or different parts of a form.
- The drop target for components should have increased top and bottom margins, making it easier to precisely position the component within a container, panel, or column.
- The drag-and-drop functionality should respond smoothly and consistently without instances of components resisting movement.

#### Additional Information:

1. Configurator feedback highlights challenges in adding components to busy screens or moving them within a form, with some users finding it "impossible" in certain scenarios.
2. Replicating the issue involves creating a form with a container, panel, columns, and multiple text or number fields.
3. The proposed solution is to double the top and bottom margins of drop targets to significantly improve the ease of accurately placing components.

#### Definition of Done:

- Drop targets for components are updated to include increased top and bottom margins.
- The drag-and-drop behavior is tested thoroughly to ensure a smoother and more precise experience.
- Configurator feedback indicates improved usability in placing components within complex layouts.

_See the attached  below_
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/a40de758-439d-432d-b8d6-81b2b0d7356f)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/9f3b4eb2-e82f-4144-9de5-61b4b05d3401)

**Comment by hlayisanimazuze** [comment]
It will be addressed by the zooming item #631
