### ISSUE TITLE
Unusual icons used to display password values in read mode

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#607]
#### Description:
The icons representing password values are not displaying as asterisks in read mode, compromising the security of sensitive information. This issue affects the user interface and may expose password values when they should be masked.

#### Steps to reproduce the behavior:
Link: https://function-adminportal-test.shesha.dev/dynamic/Shesha/auto-complete-component-details?id=2b29131d-0749-49d7-b276-20c74b300b2d

1. Drag and drop a text field component onto your details form: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=54a5b111-75e7-4e5d-aa88-78b2893f10c3
2. Bind the component to the property
3. On the property "Type" select "Password"
4. Save and render the above details form

#### Expected behavior
Password values should be visually represented with standard asterisks in read mode for a consistent and expected user experience.

**Screenshots**
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/3e15f176-bd16-44a8-b4ce-817827e55be2)

#### Additional Context
The password values used to display in asterisks as per the screenshot attached below:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/eed8dd7c-108e-41b5-8b31-f67d13745ebb)

_Refer to the link below_
https://function-v0-27-adminportal-test.shesha.dev/dynamic/Shesha/auto-complete-component-details/?id=838b1dd2-cc5a-45e0-b6ba-226266975bb2

**Comment by hlayisanimazuze** [comment]
Item is fixed

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/68443186-555b-491b-84ab-97993fbf58d0)
