### ISSUE TITLE
Text area data display issue in details view

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#615]
When creating a record using a text area, the data does not display on the details view when using any component to display, including the text area. Similarly, when creating a record using any other component, the data does not display on the details view when using a text area to display. Additional information is visible on the payload and preview.

**To Reproduce**
Scenario 01 (Using Text Area to Create)
Link: https://function-adminportal-test.shesha.dev/dynamic/Shesha/auto-complete-component-table 
1. Navigate to the link above and Add
2. Populate all the fields (Pay attention to the ID number)
3. Click Ok
4. Search for the record created and drill down to the details view
5. **Actual results:** ID number rendered using text area does not display

**Expected behavior**
When rendering the data using the text area, the data should display and the data created using the text area should display when rendering with any other components. i.e. text area, text fields e.tc

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/fb44fad3-90c7-4f2a-8987-05ac8cc1d482)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/f6d2bbc5-d7ba-4dc4-aa6d-2799349f3a4a)

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze fixed
