### ISSUE TITLE
Support for Macs and iOS devices compatibility on the framework

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#618]
When accessing the Shesha site on Safari, an error occurs. Ensure compatibility with Macs and iOS platforms.

**Comment by Tshepiso-R** [comment]
Excluding support for old versions of Safari >7years old

**Comment by hlayisanimazuze** [comment]
What I've observed while testing with BrowserStack is that the latest top three versions of Safari (17, 16, and 15) are functioning properly. However, versions 14 and earlier either render the site inaccessible or continuously initialize without loading
