### ISSUE TITLE
Inconsistent Display of Configured Data Across Wizard Steps

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#619]
**Description:**
When configuring wizard steps, there is an inconsistency in the behavior where the data configured on Step 1 gets automatically displayed on the subsequent steps when you set "Allow Cancel" to true. This behavior is not consistent and may lead to unexpected results during wizard execution.

**To Reproduce**
Link: https://function-adminportal-test.shesha.dev/dynamic/Shesha/table-edition

1. Drag and drop the wizard component onto the form
2. On the wizard properties, click on Configure Column Steps
3. On the Configure Wizard Steps dialog, Add three steps
4. Click on step 1 and from the  Next section, configure "Text"
5. From the Before Next Action, search and select  Show Confirmation dialog
6. Configure Show confirmation dialog Arguments
7. Check the "Allow Cancel" checkbox
8. Save and Render the form
9. You will notice that all the steps inherited the action configured in step one

**Expected behavior**
The configured data on each wizard step should not be automatically displayed on subsequent steps. Each step should have an independent data configuration despite Allow Cancel set to true

_Find the video link attached below_
https://boxfusionint-my.sharepoint.com/:v:/g/personal/hlayisani_mazuze_boxfusion_io/Eb1uydfaGG1JtfQhukDs3OwB7Oe82NwQ73A4SS9DCXO4Jw?e=09YmWr

**Comment by hlayisanimazuze** [comment]
### Related Item

- #531

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze 
@Tshepiso-R 
Fixed
