### ISSUE TITLE
Data Table fails to render time as 00:00

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#620]
If the time captured is 00:00, the dataTable does not display the time, it leaves it blank

**Steps to reproduce the behavior:**
1. Render this URL link: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/Books-Table
2. Search for `TestTime Picker 4`
3. Check the `time `column 
4. Click on the magnifying glass to drill down to details view
5. Check the `time` value
6. Actual Results: The `dataTable` does not display the `00:00` value on the table

**Expected behavior**
The exact value sent to the back should be rendered on the `dataTable`

NB: The display component used is `'default'`. If you use a `timePicker` display component, the `dataTable` is able to render 00:00, however it breaks the other values

<img width="960" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/38b91ed9-83a0-46b6-b6cb-6fa8ee682152">

<img width="946" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/f9e2a0ca-77cf-4a0d-9dd5-66dca13f19a5">

<img width="949" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/b6edbd51-b7d7-47bd-a382-2b233821f7b1">

**Comment by hlayisanimazuze** [comment]
### Related Item

- #621 
- #533 
- #532

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
