### ISSUE TITLE
Time Picker display component renders incorrect value captured in the DataTable

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#621]
TimePicker display component shows consistent 02:00, despite captured time being different in the time property column

**To Reproduce**
1. Render this URL link: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/school-timespan
2. Click on 'Add' button
3. Enter all the details including time value
4. Save the record
5. Check on the table and compare the value showing with what you have captured
6. Actual Results: The column display 02:00, while the time captured is different

**Expected behavior**
The TimePicker display component should correctly display the captured time from the time property column, rather than consistently showing 02:00

NB: If you use a default display component, the dataTable renders the correct value except 00:00

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/868ce2e2-3874-4559-a230-44e90a6da4b9)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/789f19ba-f04e-47fd-8a88-9ee343d5dbf8)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
