### ISSUE TITLE
Support for multi-selection data on a data table

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#622]
Multi-selection data is currently not supported on the data table; records with such data do not display in the table.

### Acceptance Criteria
- The data table should display multi-selected data
- The inline editing and adding components should support multi-selection

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Which multi-selection are you referring to?

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, here's an example: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/reflist-test-table. This functionality should cover for reflist and entities if possible.

On the table, I have communication language which is a multi selection reflist. The value does not display on the table due to that. 

The 'Add' button also has the communication language configured. If you create a new record and check it on the table, the communication language won't display.

**Comment by IvanIlyichev** [comment]
Hi @AlexStepantsov. I've implemented my part of changes but realized that components visibility works on the inline editor settings page, most of settings should be hidden. It's related to your latest refactoring. Please fix it and notify @hlayisanimazuze.

**Comment by hlayisanimazuze** [comment]
Thank you @IvanIlyichev . I've created a separate item: https://github.com/shesha-io/shesha-framework/issues/677 to address the comment you made cc @AlexStepantsov
