### ISSUE TITLE
Default active step not functioning properly with JavaScript

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#625]
I'm using gender value to get the default active step dynamically. 

**Steps to reproduce the behavior:**
1. Render the designer URL link: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=852e8104-7ca4-4686-8a76-f1c4efd05c3f
2. Click on 'Wizard' component
3. Scroll down to 'Default Active Step'
4. Click on code editor
5. Check the path provided to get the gender value
6. Render this link: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/newchanges-table1
7. Select a record from the table and click on 'Get Wizard' button
8. Actual Results: The wizard always default it to step 1, even if the gender has a value

**Expected behavior**
Based on the gender value provided, it should default it to the correct step

Example of how we used it before: https://function-v0-27-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/refcomponent-table/
1. Select a record from the table and click on 'Get Member' button
2. Actual Results: The value is redirected to the correct step

**Comment by hlayisanimazuze** [comment]
### Related Item
- #531

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze fixed
