### ISSUE TITLE
Key information bar component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#635]
### Description
- The request for this item is to make the Key information bar into a configurable bar component. It should automatically stack horizontally and have top aligned labels by default. Each section will be separated by a vertical separator. 

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/48775fb9-36e6-4d7b-a7de-338fee627aab)

### Related Item
- #581

**Comment by hlayisanimazuze** [comment]
Hi @czwe-01 , please see the below adjustments on the component

- Should be able to adjust the padding inside the column
- Revert to default height when the height property is empty/removed
- Alignment of the columns. By default the alignment of the columns are left aligned and leaves a huge space on the right. Can we have a flexibility to align the columns? If columns properties are used, it leaves a grey space
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ff6c6ec4-3152-47b4-afc7-28eca4f6a236)
-The size of the column is defaulted to 200, even when it is updated it still renders 200
-Check the wrap functionality when the value is longer than the size of the column example: entity reference cuts the value

**Comment by Tshepiso-R** [comment]
1. On the Configure Colum Dialog, remove the tooltip from the width and padding input fields to the heading.
2. The padding does not work  when you do not specify the units

**Comment by miracleMa** [comment]
Relate Item

 #1957
