### ISSUE TITLE
The wizard component breaks when using JS to configure wizard steps

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#641]
**Issues**
- The component breaks when you use JS to specify the properties, Title, Sub Title, and Description e.g `return "Personal Info"`
- When configuring Icon using Js it does not display when you render
- Disabled and Custom Disabled properties do not disable the step
- JS does not work when configuring the Text property under Next button, Back button, or Done button

**Repro Steps**

https://function-adminportal-test.shesha.dev/dynamic/Shesha/wizard-component-test-table

1. Click on the link and navigate to the form designer
2. From the wizard properties, click Configure Wizard Steps.
3. Click on step 2 and on the property "Title", use JS to return the title
4. **Actual Results:** The component break and display the error below
5. Check the "Diaabled property or use JS"
6. **Actual results:** The step does not get disabled when you render
7. On the Icon property, switch to JS and return any icon name
8. **Actual results:** the icon does not display
9. Navigate to either Next button, Back button,or Done button and configure the name Text property using JS
10. **Actual results:** The configured Text does not display

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/a5264021-0bbc-4d7b-8c21-6f79998beb2d)

**Comment by Tshepiso-R** [comment]
Hi, @AlexStepantsov 
1. I have noted that you can't use a condition to configure a property when configuring the wizard steps, 
E.g. If you want to disable a step based on a condition, you then write `return data.checkbox1`  or `return contexts.appContext. checkbox1 the Disabled property. 
When you use this method, it does not respond accordingly. 
2. The Disabled property is still not working, since we still have the property Custom enabled, are we supposed to focus on it not?

**Comment by AlexStepantsov** [comment]
hi @Tshepiso-R 
Fixed

The "Disable" property was added by mistake. I deleted it. Please use "Custom Enable".

PS: But the meaning of Disabling is not very clear to me, since the step is still allowed for selection and it is more logical to use visibility.
I was not initially involved in the development of the component, so I cannot explain the implementation details.

**Comment by Tshepiso-R** [comment]
Hi @AlexStepantsov  Noted, Thanks.
