### ISSUE TITLE
Dynamic no-auth pages have been disabled on the latest version of shesha

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#659]
Users should be able to access the reset password without logging in to the system. Currently, when you click on the no-auth page, it redirects to the login page instead of reset password.

**To Reproduce**
1. Go to 'https://pd-agrierp-adminportal-test.shesha.dev/no-auth/boxfusion.agrierp/user-password-reset/?token=1'. Ensure you've logged out first
2. Actual Results: The link redirects to login screen

**Expected behavior**
The link should redirect to the reset password no-auth screens.

**Comment by hlayisanimazuze** [comment]
@IvanIlyichev I also need this change onto the release 0.28 I'm currently testing, that is what I will publish for the other project to use. The merge should not bring changes that are on main which I haven't tested and it should not change my change log notes since we use that as a release notes

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check. I have not updated ArgiErp project, only @shesha/reactjs

**Comment by hlayisanimazuze** [comment]
@IvanIlyichev , thank you. Let me test it, they will update once I push the release
