### ISSUE TITLE
Switch values do not display when rendering in details view

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#665]
The value showing on the details view, does not correspond to what the API brings back

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Shesha/mobiledevice-details?id=9eddef23-c101-443f-93da-508e1a065597'
2. Check the switch value(is false)
3. Click on the edit pencil(the switch shows that the value is true)
4. Actual Results: On the details view, the switch component does not show the true value, it is always false until you edit

**Expected behavior**
The value should show according to the what the API brings back

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ce1fe3dd-6344-4dcc-bd6d-bfe177e53edb)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/70c983a8-fbaf-4086-91ee-d01c37829578)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. Please check it, it was closed automatically by merge
