### ISSUE TITLE
Display details of ScheduledJobStatistics in Quickview component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#684]
### Description
This is an enhancement to [#35770](https://dev.azure.com/boxfusion/e00c3e70-45fc-4fd4-aa56-5ab0f9bebb4b/_workitems/edit/35770) 

Job statistics currently get displayed by simply showing the stats in raw Json form within the Scheduled Job history table.

This can be improved based on enhancements to the DataTable component implemented here [#12288](https://dev.azure.com/boxfusion/e00c3e70-45fc-4fd4-aa56-5ab0f9bebb4b/_workitems/edit/12288)

### Acceptance Criteria
1. Allow JobStatistics to be displayed to the user in a properly formatted way, either through a Quickview pop-up or within the table cell.
2. Should be able to specify the default QuickView/ListItem forms for rendering the JobStatistics in the administration UI. If not specified should just display Json (perhaps with some basic formatting)

**Comment by ihouvet** [comment]
Merged into #704
