### ISSUE TITLE
Clean-up configurator toolbox for Beta release

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#692]
**Description**
Current list of form components is very long, poorly organised, confusing and overwhelming:

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/501a457c-4b0f-4804-b84e-1f310b1030c8)

**Acceptance Criteria**
a. Obsolete and duplicative components should be removed
   - There are various Text/Paragraph components that need to be consolidated and moved under basic
   
b. Components should be grouped more logically:
   -  The main groupings should be:
        -  Basic
        - Layout
        - Tables
        - Advanced
        - Enterprise (Should only be visible if Enterprise module is installed)
        - Beta (for advanced components which are not stable or polished - should ideally be hidden unless Shesha developer)
        - Shesha Configurator (should ideally be hidden unless Shesha developer)
        - Shesha Administration (should ideally be hidden unless Shesha developer)
        - HIS Components (ensure not be visible under Starter Project)
   - Components under 'Static', Custom, Permissions and Typography should be realocated to groups above
   
c. Components should be logically ordered within the groups e.g. all components dealing with attachments should be grouped
d. Some components need to be renamed to add to clarity

**Comment by Tshepiso-R** [comment]
Lukeman Elabor
[commented Mar 13](https://dev.azure.com/boxfusion/Shesha%20Web%20v3.0/_backlogs/backlog/Shesha%20Web%20v3.0%20Team/Stories/?workitem=45708#3871561)
 

Hi @Hlayisani Mazuze and @Ian Houvet please provide further information on this item

**Comment by hlayisanimazuze** [comment]
A separate card will be created to address some of the components that need to be renamed to add to clarity
