### ISSUE TITLE
Create Permissions component that allows one or more permissions to be specified

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#693]
**Description**
Access to APIs and functions on the UI is restricted by specifying which Permissions are required in order to access the function. We therefore need a standard component that allows users to specifying one or more Permissions in an easy way.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/8bea28ed-e159-4ff0-86cc-57c3a9c74acd)

**Acceptence criteria**
Should have a form component that can be reused throughout the configuration environment for the selection of one or more 
   Permissions.
The component should:
   - Allow selection of Permissions as autocomplete control
      - The autocomplete list should be based on the list of Permissions defined through configuration
      - The auto-complete list should also indicate which module the permission is defined in 
   - Allow multiple permissions to be selected with each permission selected added as a 'Chip'

**Comment by hlayisanimazuze** [comment]
A permission component has been created and it is available on developer mode. What's outstanding is to add/replace the new component on the existing settings of all components. Any follow up items will be created separately once the full integration and testing has been done
