### ISSUE TITLE
Allow Permissions to be selected from a list rather than entered as free text when configurator specifies required permissions

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#701]
### Description:
Allow Permissions to be selected from a list rather than entered as free text when configurator specifies required permissions

**Comment by hlayisanimazuze** [comment]
Related Item: https://github.com/shesha-io/shesha-framework/issues/693

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze

I have added `permissions?: string[];` field to the base components interface (`IConfigurableFormComponent`) and added common handling this property.

Need to update settings forms for all components and add PermissionAutocomplete component (or replace current used components for `permissions` field).

Examples for different types of settings forms:
..\shesha-reactjs\src\designer-components\wizard\settings.tsx
..\shesha-reactjs\src\designer-components\textField\settingsForm.json
..\shesha-reactjs\src\designer-components\button\settingsForm.ts

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, Please review the areas below where updates are still required


- Entity Configuration>>CRUD APIs
- Side menu>>group and item menu
- TableViewSelector?
- Wizard>>Configure Wizard steps
