### ISSUE TITLE
Required permissions of 'Navigate to' menu items should automatically be inherited from the required permissions of the targeted view

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#711]
Dependency on this item: #710 

Once implemented the Required permissions of 'Navigate to' menu items should automatically be inherited from the required permissions of the targeted view. This will avoid duplicate configuration.

**Comment by AlexStepantsov** [comment]
Hi @hlayisanimazuze 

The menu item has permission and the form/view has permission.

1. What need to do when choosing a form for menu item in the desiger? Should menu item permissions be automatically set to form permissions?
2. Should it be allowed to change permissions of menu item configured as `navigate to` action?
3. What need to do if form permissions will be changed later? This will lead to inconsistent permissions from the menu item and the form
4. Based on above. What permissons need to use to check on the rendered menu in the following cases:
4.1. The menu item doesn't have permissions and the form has permissions (probably use the form permissions)
4.2. The menu item has permissions and the form doesn't have permissons (probably use the menu item permissions)
4.3. The menu item has permissions, the form has permissions and these permissions is not the same (?)

I think the best way - is not to automatically set permissions for menu item in the designer , but to check the form/view permissions when rendering the menu if the menu item doesn't have permissions

If a menu item has permissions, we should use them to check.

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, I just confirmed with @ihouvet, when `navigate to` option is used, we need to hide the permission property and not allow users to configure the permissions from the menu level. The menu item inherit from the form/view permissions

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, with the current implementation, the side menu does not seem to inherit from the view/form level permissions when the permissions are specified on the view/form level. Example: https://function-adminportal-test.shesha.dev/dynamic/TestModule/anony-table

Login as: `loginT `and password: (the default password we use on function)

- From the side menu, scroll down and click Permissions menu item
- Upon clicking, the form will display 'Sorry, you are not authorized to access this page' to show that the user does not have the required permissions, however the side menu still shows
- Expected Results: When the side menu inherits from the view/form level, upon logging in, it should check the permissions assigned to the current user logged in and hide/show the side menu item accordingly 

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a1af709e-3dbc-46ef-ae32-1cbe5e5f2ffa)


![image](https://github.com/shesha-io/shesha-framework/assets/151041759/c1b3070c-b050-4569-90c6-c10a5886116b)
