### ISSUE TITLE
The custom endpoint does not execute when the form is rendered

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#736]
If your `dataTableContext` uses a custom endpoint, when you render the form it does not get called

1. Navigate to the configuration form: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=c3b1d5f5-dcc6-4957-b45f-34bdc9f59d95
2. Click on the membership payement dataTableContext
3. Verify the custom endpoint ended on the property
4. Render the form: https://function-adminportal-test.shesha.dev/dynamic/Shesha/member-details-view?id=b7f0594e-9a6b-478d-bf35-e71962070507 and check if the endpoint is being called
5. Actual Results: The endpoint is not executed

**Expected Results**
The endpoint should be executed when the form is rendered

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ccec1a8a-dae3-4484-b47c-fe684ff7e4fc)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
