### ISSUE TITLE
Rectify the spelling on the property from "On lis item save success" to "On list item save success" on the datalist component.

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#746]
https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=a058c9cc-cfde-43e1-a4d3-968de3e2f096

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/a75be518-7ee8-49fc-9667-f953d6efe1e5)

**Comment by Tshepiso-R** [comment]
- #610

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov may you please apply the change also on the below items
- On list item save code editor
- On list item save tooltip including the hint message on the code editor
- On new list item init tooltip including the hint message on the code editor
- On list item save success tooltip

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a5d5345b-74f1-4e2c-ab22-7fc0d88f4319)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/40a593c6-a734-4077-88b4-d162084c4b08)

<img width="254" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/541fe6c2-3404-4d75-86c8-15b755200ace">
