### ISSUE TITLE
Error displayed when jumping to non-existent wizard step

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#756]
**Description**
When you use a component e.g text component to set a step using index and specify a non-existent index `contexts.wizard1.api.setStep(115)`, the component crashes instead of throwing an exception. 

**To Reproduce**
1. Go to https://function-adminportal-test.shesha.dev/dynamic/Shesha/eight-nov
2. Click on 'Add New member'
3. On step 03,  select member start date
4. **Actual Results:**  The component crashes when trying to jump to the non- existent step. 

**Expected behavior**

The component is expected to display an exception instead of experiencing a crash, as outlined in the details provided in issue #653.
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/b367553a-14d1-4522-a354-84a461ed7fe9)

**Comment by hlayisanimazuze** [comment]
### Related Item

- #653

**Comment by Tshepiso-R** [comment]
Hello @AlexStepantsov, we've observed an issue where programmatically moving to the last step using the code `contexts.wizard1.api.setStep(4)` doesn't work as expected.

For instance, consider a wizard component with 5 steps, and on the first step, a text component contains the code:

```javascript
if(data.firstName.length === 3){
  contexts.wizard1.api.setStep(4);
}
```

Despite meeting the condition, the action isn't triggered, and the wizard remains on step 1. Additionally, when using a similar code line on a button, an error occurs: `index.es.js:1 Failed to execute action 'shesha.common: Execute Script', error: Step with index 4 is not available on the console*`.


**Expected Results:**
- We should be able to move to any existing step including the last step
- An exception should only be thrown if the specified step is non-existent.
