### ISSUE TITLE
Entity Configurations reverting to original state

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#757]
When you apply formatting on the Entity Configurations, the changes seem to revert back to it's original state (I'm not sure if this could be after a major deployment)

**Steps to reproduce the behavior:*
1. Go to 'https://function-adminportal-test.shesha.dev/settings/entity-configs/configurator'
2. Search for Book/School/Member
3. Actual Results: Formatting applied on number/datefield property are reverted back to it's original state

**Expected Results**
The formatting should be based on what the user had configured and not revert back to it's original state

**Comment by AlexStepantsov** [comment]
Hi @hlayisanimazuze @Tshepiso-R 

I haven't been able to replicate this issue, but there is one option that may have an impact.
When the application is launched, various data is bootstrapped, including EntityConfigurations from the code. Configurations are not always updated, but only when there are some changes (in the name, aliase, properties, etc).

So, configurations may be reset to their original value if the original Entity class was changed in code.

**Comment by hlayisanimazuze** [comment]
I'm closing this item, the implementation of it will be covered by this item #858
