### ISSUE TITLE
Move non-core related functionality and modules outside of Shesha Care 

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#767]
The following modules and functionality should be moved out of Shesha.Core and into other repos:

Enterprise repo:
- Bulk SMS
- Azure AD
- LDAP
- RabbitMQ
- Xml2SMS
- SMS Portal

Move the following into Shesha.Mobile repo:
- Push
- Firebase

You will need to add migration into Shesha core to delete any old settings and add migrations as part of new module.

**Comment by hlayisanimazuze** [comment]
Function site still has the modules that were removed: https://function-adminportal-test.shesha.dev/shesha/settings

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/46dca530-1ef5-4580-b6e9-db2f59128c91)
