### ISSUE TITLE
The side menu label item title is missing after recent update

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#785]
**Steps to reproduce the behavior:**
1. Click on the pencil to launch edit mode and confirm from the pop-up
2. Click on the side menu to edit
3. Click on 'Add New Item' button
4. Check the button properties
5. Actual Results: The item label title property has been omitted

**Expected behavior**
The label title property should show to allow users to rename the side menu titles

Current Changes
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/1a12ce78-baef-4e6c-bc4a-0323f9b53698)

Old Changes
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ad19bce5-a5d0-408b-aebb-c125bb3f9632)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
