### ISSUE TITLE
The table columns display data in edit mode when you opt to display components using some components

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#792]
**Description:**
The data is incorrectly shown in edit mode when opting to display components using text field, autocomplete, number field, dropdown, time picker, and date picker in the table.

**Repro Steps**
Link: https://function-adminportal-test.shesha.dev/dynamic/Shesha/thirty-october
1. Create a table-view form 
2. On the form designer, go to the datatable configurations and add at least four columns
3. Bind each column to a property and  from the display component property, select the text field, autocomplete, number field, dropdown, time picker, and date picker for each column
4. Save and render the form
5. **Actual results:** When you select the display components such as number fields, dropdowns, time pickers, and date pickers to showcase data in a column, the columns automatically default to edit mode.

**Expected Results**
The data in the table columns should be displayed correctly according to the selected components (text field, autocomplete, number field, dropdown, time picker, and date picker). Edit mode should only be triggered when explicitly editing the data, and the display should accurately reflect 
the chosen components without affecting the overall table layout.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/131921e3-8703-4302-8a13-7da0eadee4ed)

Related Items:
https://dev.azure.com/boxfusion/Shesha%20Web%20v3.0/_workitems/edit/51306

**Comment by IvanIlyichev** [comment]
Hi @AlexStepantsov. It's affected by your latest changes, please check
