### ISSUE TITLE
Unable to Perform Inline edit with time picker in datatable

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#810]
**Description:**

Issue: Unable to edit datatable inline using the time picker component, when you click your desired time the component does not respond as expected.

Steps to Reproduce: 

1. Navigate to https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/Books-Table
2. On the table click the edit icon
3. Attempt to edit a cell in the datatable that uses a time picker component.
4. **Actual Behavior:** Inline editing is not possible with the time picker i.e. Time

**Expected Behavior**:
 The time picker should enable inline editing of the corresponding cell in the datatable.

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. I've fixed it, please check
