### ISSUE TITLE
Clean-up and eliminate duplications in dynamically generated APIs

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#838]
**Is your feature request related to a problem? Please describe.**
Currently the following endpoints get generated for entities but there is some duplication which may cause confusion:
- Get / Query
- Update / UpdateGql
- Create / CreateGql
- GetAll / QueryAll
- Delete

Additionally, currently when a custom end-points/AppService is created there is a risk of 'hiding' the dynamically generated crud APIs if the developer simply calls them '{{EntityName}}AppService' which is default naming devs tend to use. This catches out less experienced Shesha devs and causes unecessary confusion.

**Describe the solution you'd like**
- Eliminate the duplication
- Avoid using Gql in naming as it may be misleading since we only have limited implementation of the Gql specification 
- Dynamically generated CRUD AppServices should be called '{{EntityName}}CrudAppService' by default rather than the current 
'{{EntityName}}AppService' 
- To minimise impact on existing projects where explicit Urls are used it would be ideal if the front-end can fallback to old url naming if the end-point is not found (assuming this will not create an excessive amount of work).

**Comment by AlexStepantsov** [comment]
Need to implement feature to allow components set list of necessary fields to fetch.

For example, SubForm assigned to Member property and can be configured to work as is. But for Dynamic mode SubForm requires _className of Member with Id

**Comment by AlexStepantsov** [comment]
Implemented a feature that allows components to add required fields to a request.
