### ISSUE TITLE
Failure to prepopulate relevant additional fields for components requiring them upon selection

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#841]
On any component that supports reference list data type or autocomplete component, when you interchange the `dataSourceType`, the additional properties are not displayed immediately upon selecting, requires manual refresh. Drag a buttonGroup component and configure it, from the buttons type, select custom/interchange between the options

Components affected
- Dropdown
- Radio
- Checkboxgroup
- Autocomplete
- ButtonGroup>>>Buttons Type and action buttons
- DataTable>>Customise columns: If you select crudOperations/action, when you move to the data column, the propertyName is hidden
- Action Configuration>>Navigation Type
- Entity Configuration>>Application service

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=3304c5ea-8801-46fc-8a9f-bbd6e6ce23bc'
2. Click on `dropdown, radio and checkboxgroup and autocomplete` components
3. Scroll down to 'dataSourceType'
4. Select another option from what is shown e.g. `reference list`
5. Actual Results: The relevant additional field such as `reference list` autocomplete does not show
6. Move from one component back to the selected one/Save the changes and refresh
7. Navigate to the component
8. Actual Results: The relevant additional field does show

**Expected behavior**
Immediately when a user selects a dataSourceType, the relevant additional field(s) should display

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ad02fe91-bfad-4fea-80f1-fc793baed780)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/40ed8d0f-0bb0-46f5-8c6d-ae312e810752)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/5529a84c-ae5f-4ffb-b4d1-c7fe1db9a1aa)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/e565eb13-05ad-4f39-b99a-9bcca0a3eeaf)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3930944e-3f0d-4c04-94a6-626b7edfb12f)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ac5ed24b-757a-429f-9734-63605965874d)

**Comment by Tshepiso-R** [comment]
Hello @AlexStepantsov, kindly be aware that certain impacted components may not be explicitly mentioned on the card, and we anticipate a comprehensive resolution for this issue globally.
