### ISSUE TITLE
Implement export/import of entity configurations

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#858]
1. Generic export and import should include entity configurations. I've implemented base classes and UI, but we need to implement configuration versioning and export/import rules for entity configs.
2. Documentation about the export/import available [here](https://dev.azure.com/boxfusion/Shesha%20Web%20v3.0/_wiki/wikis/Shesha-Web-v3.0.wiki/707/Packages).
3. Some technical details:
- Back-end:
    - ConfigurationItemAppService - application service that work with packages, it allows to export/import and analyze package, works with registered exporters and importers.
    - EntityConfigExport - class that implements export of entity configs, it's already registered and works, but maybe you'll have to make changes in the exported data/format
    - EntityConfigImport - class that implements import of entity configs. It's registered but doesn't contain implementation of the import. Here you need to implement the logic
-  Front-end:
    - Dialogs for export and import support configuration items of any type but currently they show only forms. You'll need to uncomment this GQL filter to unlock other types of configuration items, check this file: src\components\configurationFramework\itemsExport\index.tsx

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/dc114dad-2299-4024-bdf9-10fa1b3af002)

**NOTE**: export/import functionality should take into account the versioning of configs and EntityConfigsBootstrapper. There should be transparent limitations and rules of the entity config lifecycle.

**Comment by hlayisanimazuze** [comment]
**Note**: When implementing this item, please ensure that an implementation is in place to prevent configurations (e.g., formatting) from resetting to their original values if the entity changes in the code

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov , we've prioritise this item in this current implementation

**Comment by AlexStepantsov** [comment]
Import/export are implemented.
Implementation is prevent configurations (e.g., formatting) from resetting to their original values if the entity changes in the code. But note that hardcoded attributes have high priority, replace configured values and Entity Configurator doesn't allow to change them

Implementation versioning of entity configurations moved to separate issue #1075
