### ISSUE TITLE
The permission configurator view is disabled

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#860]
A user is unable to click a permission and update

**TSteps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/StarterTemplate/permission-configurator'
2. Click any of the permissions
3. Actual Results: All the permissions are disabled

**Expected behavior**
A user should be able to click and update the permissions

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3084849e-50b6-4fb0-9661-8be3b11c70f5)

**Comment by AlexStepantsov** [comment]
Just fixed the setting `Edit Mode` for PermissionTree controls on the `StarterTemplate/permission-configurator` form
