### ISSUE TITLE
Tab component allows users without defined permissions to view the component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#864]
If you define a permission on the tab component, unauthorised users can still view the component

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/basic-component-table' and login with a user without the defined permission (promiser)
2. Click on 'Add' button
3. Actual Results: The tab component shows
5. Check if Membership Details tab shows
6. Actual Results: The tab does not show due to the permission applied which the logged in user does not have

**Expected behavior**
When a permission is defined on the tab component level, when a authorised user access, the component should not show

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/9c775d9e-79bb-4177-a028-01bf23008768)

**Comment by AlexStepantsov** [comment]
@hlayisanimazuze 
I think it was fixed by other fixes

I logged with promiser and Membership Details tab does not show.
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/dc092229-3f55-4de7-93f2-b4bba3a63825)
