### ISSUE TITLE
Allow background colour on a cell to be specified on DataTable column

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#865]
**Is your feature request related to a problem? Please describe.**
Cell background and font colour changes based on certain conditions (Example from AgriTech project
image
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/3e657095-43dc-4a10-bfcf-9a15e35475f4)

**Describe the solution you'd like**
1. A new 'Background color' property should be available on the column definition of a datatable
1. This should support JS definition so that it may be calculated.
1. The JS script should be able to reference the current rows values.

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's implemented, please check
