### ISSUE TITLE
The edit mode property on Subform Component does not work as expected despite configuration settings

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#872]
**Describe the bug**
If you update the edit mode settings, the component does not behave according to the configuration.
Example:

- If you set the component to readOnly, you can still edit it
- If you set the component to editable, it is not always editable. It only behaves when you click the form edit button(This is on details view)

**Steps to reproduce the behavior on create form:**

1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/school-subject%20test?id=78c6e519-8742-4eb7-86a3-011f5c63d481'
2. Navigate to the form designer mode
3. Change the Edit mode to "Editable"
4. Save and render the form
5.  **Actual Results:** The Subform component is always on inherit mode re

From rendered:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/42fde715-3ec1-4425-878a-684045657ba6)

Form designer: 

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/38b166b3-9fd7-4ecf-970b-1cc192822fa9)

**Comment by hlayisanimazuze** [comment]
Hi @AlexStepantsov, this looks to be working as expected now. We will re-open it if we encounter the same issue again
