### ISSUE TITLE
Form configurator should be able to support different canvas sizes to more accurately reflect the expected layout

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#888]
**Is your feature request related to a problem? Please describe.**
The form configurator currently assumes that the form being configured is targeting the full working area for its layout. This is of-course not the case if the form is intended to target things like: mobile, sub-form for rendering list item, dialog box, header bar, etc…
Allowing the user to specify for each form the type of target or layout would therefore helpat configuration time to better approximate the expected layout at run-time and give the configurator a better sense of the expected layout.

  *   Mobile app
  *   Header section
  *   List item sub-form
  *   Panel sub-form

**Describe the solution you'd like**
Need to think how best expose but one option could be to add a ‘Target layout’ property at the form level. This would then adjust the canvas size of the form accordingly.
Possible values could include the following:

     *   Standard web form (I.e. assumes have the dimensions of the full web-area)
     *   List Item
        *   Full width
        *   1/3 width
        *   1/2 width
        *   2/3 width
     *   Dialog
        *   Small
        *   Medium
        *   Full screen
     *   Header / Footer (I.e. full width but not very tall)
     *   Mobile
        *   Portrait
        *   Landscape
     *   Tablet
        *   Portrait
        *   Landscape
    * Custom - configurator/form template able to specify custom dimensions

**Comment by hlayisanimazuze** [comment]
The above requirements are not implemented fully on the current changes. A separate card is created to cover the full requirements. 

What we have at the moment, desktop, tablet and custom-width options
