### ISSUE TITLE
It should not be possible to assign configuration to a module which is not in development

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#891]
**Is your feature request related to a problem? Please describe.**
Any configuration item needs to be associated to a module. It should however only be possible to assign configuration item to a module that would be able to embed that configuration I.e. module(s) in active development.
Currently when creating a new form for example, it is possible to assign the configuration to any module including modules imported via Nuget.

**Describe the solution you'd like**
- The list of modules to assign new configuration to should be restricted to modules implemented by the solution itself.
- If it is not possible to autodetect whether a module has been imported as DLL/Nuget or where source is available, then will need to introduce a ‘IsConfigurationEditable’ property for all Shesha Modules

**Comment by AlexStepantsov** [comment]
Need to add DefineConstants to the code of module
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/7c97c7d2-2fb3-404d-9f85-4ec5b3e54248)

And then add it to the Release custom symbols
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/f0768a98-4aba-4989-a6cc-858d49a03227)


or the best way - configure build (yaml, etc)
![image](https://github.com/shesha-io/shesha-framework/assets/125558744/b985edc8-9b88-4f7a-a41e-597c99bee3da)

after this, all modules with this constant in the released assemblies will be set to `IsEditable = false`
