### ISSUE TITLE
Enhance Image component to be able top support additional image sources

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#892]
**Is your feature request related to a problem? Please describe.**
The current image component only supports limited sources for the image which is very limiting for certain use cases.

Amongst other things, this feature is intended to allow the logo on the header and login page to be configurated when combined with #601 .

**Describe the solution you'd like**
It will also allow other use cases to be supported (e.g. GeoInt SpeedFox where different logo should be displayed based on the logged into user and their PrimaryOrganisation).

Image component image source type:
1. URL:
    1. Can be static or expression based
    1.  Would have to be read-only
1.  StoredFile property
    1.  Property to bind to
1.  Base64 (string property)
    1.  Property to bind to
1.  AppSetting
    1.  Modulename
    1.  AppSetting name
1.  For all above:
    1.  Is editable: Yes, No, Inherit

**Comment by hlayisanimazuze** [comment]
Separate the card and create a new one that supports app settings
