### ISSUE TITLE
The `Dropdown` and `Autocomplete` components are appearing smaller than expected

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#905]
The size of `Dropdown` and `Autocomplete` components are small which is so difficult to search and select from them

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/afterupgrade1-table'
2. Click on dropdown/autocomplete components
3. Try to search and select the values
4. Actual Results: Both components are smaller and it is so difficult to use them

**Expected behavior**

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/78d40da9-8ed3-41cb-a5b2-edf308aeb56e)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/e54b1830-e371-4c6b-936f-ae8257598f3c)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/9c5e28ed-263d-4949-a189-ac216ac5badb)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
