### ISSUE TITLE
Inconsistency of the designer view within a `Quick Edit` and `Full View` forms

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#907]
List Of inconsistencies
- The position of Settings and the 4 icons
- The size of the builder widgets grouping and data is bigger compared to full view
- The component names are smaller and they are not within a borders compared to the full view

**Steps to reproduce the behavior:**
1. Full view link: https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=c9621706-fb64-485e-9eb4-31d1ff949291
2. Quick Edit: https://function-adminportal-test.shesha.dev/dynamic/Shesha/wizard-component-test-table
3. Click on 'Add' button and navigate to the quick edit

**Expected behavior**
The settings should be on the right hand side

Full View
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/d792a37f-611a-4be9-8c26-72949828c5a3)

Quick Edit View
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/b277f2ff-1680-4f06-b749-c7e4662b4245)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/8659938b-2576-45c9-914c-f589a256a7c1)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/37162f4d-1d6c-4600-8e30-30e31080e17c)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3f0f13f1-4aed-4d25-986d-bc904a3d4407)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/11f6d72d-9afc-4d23-af95-8c8c0d89c286)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
