### ISSUE TITLE
There's a slight delay/pause from dragging and dropping/deleting/editing/clicking the components

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#910]
When you drag and drop a component, a pause occurs before the component gets dropped. Similarly, when you type in any property, the characters typed take some time before displaying. 

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=8e35053f-1d68-4c77-b865-d3e03c434899'
2. Drag and drop a component from the builder widgets onto the container
3. See the behavior before the component gets dropped
4. Attempt to configure any text field property or text area property
5. Observe that the characters typed do not display instantly.

**Expected behavior**
There shouldn't be any delay between the events

**Comment by IvanIlyichev** [comment]
Hi @AlexStepantsov. I've made part of optimization, please review settings controls.
