### ISSUE TITLE
Fix the step/tab configuration layout design for `Tabs and Wizard` component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#911]
Initially, the tab wizard steps were configured in a horizontal layout. Currently, they are arranged vertically, causing confusion when attempting to click on a step and occupying more space.

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=8e35053f-1d68-4c77-b865-d3e03c434899'
2. Click on 'Tab/Wizard' component
3. From the properties panel, click on `configure tab panes`
4. Click on 'Add New Item'
5. Actual Results: The steps are listed vertically, instead of horizontally

**Expected behavior**
The steps/tab panes should be listed vertically. See the old design

**Old Design**
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/ce360955-1206-44a2-aa0f-6aa1ba3676f7)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/b7f1a56d-b1ec-45be-a1a1-bc0aecbf0c6c)

**New Design**
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/0e2d2ac8-4c06-413c-8f90-d292ff2efa9a)

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/20d2cae2-3907-4347-ba7c-604aa6eef36d)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
