### ISSUE TITLE
Move red asterisks to the right-hand side of the component label

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#913]
The asterisks should be moved from the current position to the right-hand side. Refer to the example below

Implementation required
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/838e0892-fe2e-48fc-9f15-8714b91f3583)

Current implementation
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/7f0313a2-8fb3-43b4-8421-5b2948fd2905)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, the below components are not updated, the rest are updated

- ChildEntitesTag>>label format
- Button Group>>component name
- Datalist>>component name
- Columns>>component name
- Sizable Columns>>>component name
- Tabs>>>component name and default active key
- Wizard>>component name
