### ISSUE TITLE
The borders of the autocomplete component are hidden

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#917]
**Description**
The borders of the autocomplete component do not display after dragging and dropping the component.

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/twenty-two'
2. Click on the 'Add' button
3. Drag and drop the autocomplete component
4. Observe that the component's borders are hidden

**Expected behavior**
When you drag and drop the autocomplete, the border should display immediately.
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/c8fd9e71-331b-42cf-b3f9-7c91277d0c41)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/c5a36ae8-ee34-467d-99dc-9ca91e8707f3)

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev , I see this item is fixed, however it has affected `hide border` property. If you set it to true, the border does not get removed/hidden anymore when the component is rendered

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/6270d84b-5965-4200-8705-0fa2bb83d33b)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
