### ISSUE TITLE
Hide border property on the autocomplete compinent is  not working as intended

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#920]
**Describe the bug**
When "Hide border"  is true on the autocomplete component the borders still display. 

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/twenty-two'
2. Click on 'Add' button 
3. Drag and drop the autocomplete component
4. Check the hide border property or us JS to return true
5. Save and render the form
6. Observe that the borders still display even when true is returned

**Expected behavior**
When you return true or check the hide border property, the borders should be hidden

Form configs:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/88944610-4da2-4a30-93eb-d4340e879437)

Form rendered:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/e2584470-b169-42f2-9769-0ef801e4b96b)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
