### ISSUE TITLE
Endpoint fails to pass filtering parameters

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#935]
If I have a form on the details and the data rendered on the child table should be filtered. When you render the form, on entity name it does not append the id or if you are using a custom endpoint, the parameter appended on the endpoint fails e.g. `{{data.id}}` or `memberId={{data.id}}`

**TSteps to reproduce the behavior:
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/submitform-details?id=466d8453-e8c2-47de-afa1-0cf075a83c81'
2. Open your network and check the endpoints called
3. Actual Results: GetAll endpoind does not append the id on the filtering/custom endpoint says the value '' in invalid

**Expected behavior**
The filtering should execute successfully

NB: This also occurs when you use the tableviewselector/permanent filter from the dataTableContext/custom endpoints
<img width="959" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/dc089879-044d-407d-a7c2-d8d4fb664ef6">

<img width="988" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/36f3dd09-47d2-4b6c-85f4-b3c7204f501e">

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
