### ISSUE TITLE
Align the values of Entity reference for Quickview Entity Reference type

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#936]
## Description
Data displayed using entity reference component with entity reference type `Quickview` and not aligned with values displayed with other Entity Reference Types and other components

## To Reproduce

1. Drag and drop the Entity Type component to a details form
2. Configure all the necessary properties
3. On the Entity Reference Type, select Quickview
4. Drag and drop two more Data Properties e.g. autocomplete or entity picker to compare the alignment
5. When the form is rendered you will notice that the values for the entity reference are shifted to the right compared to the values of the other components

## Expected behavior
Quickview values must be aligned with the values for all the other components. 

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/ba8cdd2c-5ea1-40fc-9470-5541953872db)

**Comment by Tshepiso-R** [comment]
Hello @IvanIlyichev, we've observed that this problem extends to values displayed when utilizing the `AutoComplete` and when `Use Quickview` is set to true.

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It was fixed earlier, please check
