### ISSUE TITLE
Subform does not call the necessary method to get the data

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#938]
When a subform is executed, it does not get the data. The configured form used entityName and API to get the data, however when executed all the methods are not called

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/submitform-details?id=b7f0594e-9a6b-478d-bf35-e71962070507'
2. Check the subform
3. Actual Results: All the `subforms `are not getting the data, regardless of any configuration setting provided

**Expected behavior**
The necessary method should be executed in order for the `subform `to get the data

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a96f8346-49d6-4430-a517-231c8029d742)

<img width="959" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/62055490-37f8-47bd-aab9-efc442e7ae1c">

<img width="951" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/999d9480-5245-48fd-9cd5-9add77a8503c">

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
