### ISSUE TITLE
Error display when displaying using `Reference List status` on the datatable

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#939]
## Description:
When you displaying data using the component `Reference list status`, an error  *Something went during Reflists fetch* is displayed when you render.

## Repro Steps:

1. Open [Form Render](https://function-adminportal-test.shesha.dev/dynamic/Shesha/test-data-night)
2. Observe the error display on the column `Title`
3. Navigate to the form designer to verify the configurations

## Expected results:
When displaying data using `Reference list status` the data, the values should not display errors.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/6d1845f6-b8ff-49ca-a223-5dabbd445b20)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It was fixed earlier, please check
