### ISSUE TITLE
Quick links need to open in a new tab

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#949]
The quick links present on the Shesha get started screen currently open in the same window when you click on them. The request is to please have them open in a new tab to retain the users position while they follow the guide. 

https://starter-adminportal-test.shesha.dev/

![Shesha Get Started Quick links](https://github.com/shesha-io/shesha-framework/assets/153498650/39a94872-b6e0-4a5b-ac88-25124c8bd053)

**Comment by hlayisanimazuze** [comment]
This item has been implemented
