### ISSUE TITLE
When 'Use Quickview' and 'Show time' are checked, associated properties do not display

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#955]
### Description:
When checked, the `Use Quickview` property in the AutoComplete component does not instantly display the associated properties. Currently, after enabling the `Use Quickview` checkbox, the properties `Form Path`, `Get Entity URL`, `Display Property Name`, and `Width` are not immediately shown. Users must perform additional actions such as clicking on another component or saving and refreshing the page to visualize the associated fields. Similarly when checking the property `Show Time` the property `Default time to midnight` does not display instantly

### Steps to Reproduce:
1. Open https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=f134a1bd-e88c-43c8-bb45-219e0bc61c78
2. Drag and drop AutoComplete component
1. On the property panel, scroll down to the property `Use Quickview` and check it
2. Observe that the associated properties do not display.
3. Click on another component and go back to the autocomplete property and observe that the properties now display
4. Drag and drop, a Date field component and scroll down to the property `Show time`
5. Observe that the property `Default time to midnight` does not display instantly

### Expected Behavior:
- When the `Use Quickview` checkbox is selected, the associated fields ( `Form Path`, `Get Entity URL`, `Display Property Name`, and `Width`) should be promptly displayed without the need for additional interactions.
- When the `Show Time` checkbox is selected, the property `Default time to midnight` should display instantly displayed without the need for additional interactions.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/5e880ce6-3b5b-4940-8983-612f870679fb)

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/10031e34-07be-4a21-b5b5-8ac431727efb)

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/60c29322-e5c6-4a2f-bc0a-1c71036fdc88)

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/a7c20f21-7d94-4f0b-a4c9-18417606ce6a)

**Comment by hlayisanimazuze** [comment]
This is also occurring on SortMode>> Strict, allow reordering property does not display until you navigate from one property to another. This should be fixed globally, for other items that are not listed here

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/cf20f666-bbb2-4201-8d13-53bce585916d)
