### ISSUE TITLE
Default Form to currently edited module

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#956]
When you navigate to Shesha configuration -> Forms and then create a new form, the request is that we kindly default the module field to the currently edited application module.

https://starter-adminportal-test.shesha.dev/dynamic/shesha/forms

![Default Module](https://github.com/shesha-io/shesha-framework/assets/153498650/a149d06c-f6f7-4763-a846-b8ff058e0d79)

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, please apply the same filtering when a user creates a copy of the form
<img width="959" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/93a276d0-7810-4058-82a1-be456ea38c3f">

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, the above is still not updated. Even on starter project, it's not updated
<img width="938" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/f7719f94-9bc9-4d6b-b936-d564c71a8229">
