### ISSUE TITLE
Remove Label from new Form

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#958]
When you navigate to Shesha configuration -> Forms and then create a new form, the request is that we remove the label field as it is not important and not required.

https://starter-adminportal-test.shesha.dev/dynamic/shesha/forms

![Label Remove](https://github.com/shesha-io/shesha-framework/assets/153498650/193a437a-c42d-4224-b63b-23edf253e7e0)

**Comment by hlayisanimazuze** [comment]
Hi @OmolemoBlessingLethuloe, also remove the `label `column from the table view in support for this item

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/8cd4beda-0a49-4f5d-a41b-9e8088299fe8)
