### ISSUE TITLE
Delay in displaying properties panel when dragging/clicking on a component

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#959]
**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=201875fd-ad55-4364-a08b-fd7607023968'
2. Drag and drop a component and check the properties panel
3. Click any existing component and check the properties panel
4. Actual Results: The properties panel delays to display the properties

**Expected behavior**
The properties should display immediately from dragging/clicking the components

<img width="620" alt="image" src="https://github.com/shesha-io/shesha-framework/assets/151041759/9960a39d-23b1-4cbc-be8a-004b6e33090f">

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. The performance has been improved after the latest refactoring , please check
