### ISSUE TITLE
Need to make Theme configuration more explicit

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#964]
On Shesha when we navigate to the Themes configuration it is not quite explicit enough that the expected behaviour is that we modify on the left and see the results on the right. 

Here are some changes we can apply to this screen to make it more clear to users: 

1) Have bolder titles on the left and right panels. eg: 'Theming Parameters' and add supporting info/tool-tip
2) Include a small description below parameters that says "You can modify the values by selecting the colour block"
3) Making the Properties panel full height so that it looks more like a properties panel. Currently the results section is too dominant and you might not notice the parameters panel is customisable.

https://starter-adminportal-test.shesha.dev/settings/theme

![Theme](https://github.com/shesha-io/shesha-framework/assets/153498650/7c5c9434-8d20-4d9d-82b3-1ad27444cebe)

**Comment by James-Baloyi** [comment]
@AlexanderSlavchovUX about the 3rd point, do you mean that the parameters panel should always span from the bottom of the header to the very bottom of the viewport?

**Comment by AlexanderSlavchovUX** [comment]
Hey @James-Baloyi 

For now can we start by just ensuring that the parameters panel is full length to the bottom. Please don't make any changes to the margin at the top so that it remains consistent with the results screen. 

I think once it stretches to the bottom of the screen it will really help separate these two. :)
