### ISSUE TITLE
Formatting for nested entities in referenced table

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#978]
- lat-long are number properties, I tried applying the currency format on Address entity, when I tap on the address using `address.latitude/address.longitude` within School entity, the lat-long do not come with the formatting I've applied on the table, however when you hover on the address quickview it shows the formatting.

**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/referrence-table'
2. Hover over on the quickview and check the lat-long properties which shows some formatting applied
3. Check the lat-long columns, the formatting showing on the quickview did not apply on the two columns since I used the tapping method onto the entity

**Expected behavior**
The formatting should apply when a user tap on an entity property that has a formatting applied on it

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/dcf3f105-3da1-48ae-95d1-4948f356d7e4)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check
