### ISSUE TITLE
Modal Buttons display despite settings 

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#992]
## Description
When utilizing the Modal dialog box **Entity Reference** type, the modal buttons persistently display even when the Show Modal Buttons option is set to false. Similarly, the modal buttons continue to appear when Allow New Record is enabled on the **Entity picker**.

## Steps to reproduce the behavior:

1. Navigate to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/book-twenty-two'
2. Click on 'Add'
3. Open form designer mode.
4. Drag and drop an **Entity Picker** component and configure it.
5. Enable the Allow New Record option.
6. Ensure that Show Modal Buttons is set to false.
7. Save and render the form.
8. Click on the Entity Picker and select the Add New button.
9. Observe that the modal buttons persist despite the Show Modal Buttons setting.
10. Similarly, within the details form, add a new **Entity Reference** and select the modal box dialog entity type.
11. Do not select the Show Modal Buttons option.
12. Save and render the form.
13. Observe that the modal buttons still display.

## Expected behavior
When Show Modal Buttons are set to false or when Allow New Record is enabled without the modal buttons option selected, the modal buttons should not appear in the **Entity Picker** or **Entity Reference** modal dialog.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/f4244f4b-ac2d-4a50-93b6-1f97cb07ab63)

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/dac9e84c-4485-44aa-9675-003aa73e533d)

**Comment by hlayisanimazuze** [comment]
Hi @James-Baloyi , I see your PR has been merged, however not everything from the card is completed. The work item mentioned two components experiencing the same issue and your change only applied to one component

**Comment by hlayisanimazuze** [comment]
I'm consulting with a developer on ways we can pass the newly created item to the entity picker when using a custom button. A separate card will be created to accommodate that
